// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: oghamproto/ir/types.proto

package ir

import (
	common "github.com/oghamlang/go/oghamproto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScalarKind int32

const (
	ScalarKind_SCALAR_KIND_NONE ScalarKind = 0
	ScalarKind_BOOL             ScalarKind = 1
	ScalarKind_STRING           ScalarKind = 2
	ScalarKind_BYTES            ScalarKind = 3
	ScalarKind_INT8             ScalarKind = 4
	ScalarKind_INT16            ScalarKind = 5
	ScalarKind_INT32            ScalarKind = 6
	ScalarKind_INT64            ScalarKind = 7
	ScalarKind_UINT8            ScalarKind = 8
	ScalarKind_UINT16           ScalarKind = 9
	ScalarKind_UINT32           ScalarKind = 10
	ScalarKind_UINT64           ScalarKind = 11
	ScalarKind_FLOAT            ScalarKind = 12
	ScalarKind_DOUBLE           ScalarKind = 13
)

// Enum value maps for ScalarKind.
var (
	ScalarKind_name = map[int32]string{
		0:  "SCALAR_KIND_NONE",
		1:  "BOOL",
		2:  "STRING",
		3:  "BYTES",
		4:  "INT8",
		5:  "INT16",
		6:  "INT32",
		7:  "INT64",
		8:  "UINT8",
		9:  "UINT16",
		10: "UINT32",
		11: "UINT64",
		12: "FLOAT",
		13: "DOUBLE",
	}
	ScalarKind_value = map[string]int32{
		"SCALAR_KIND_NONE": 0,
		"BOOL":             1,
		"STRING":           2,
		"BYTES":            3,
		"INT8":             4,
		"INT16":            5,
		"INT32":            6,
		"INT64":            7,
		"UINT8":            8,
		"UINT16":           9,
		"UINT32":           10,
		"UINT64":           11,
		"FLOAT":            12,
		"DOUBLE":           13,
	}
)

func (x ScalarKind) Enum() *ScalarKind {
	p := new(ScalarKind)
	*p = x
	return p
}

func (x ScalarKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScalarKind) Descriptor() protoreflect.EnumDescriptor {
	return file_oghamproto_ir_types_proto_enumTypes[0].Descriptor()
}

func (ScalarKind) Type() protoreflect.EnumType {
	return &file_oghamproto_ir_types_proto_enumTypes[0]
}

func (x ScalarKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScalarKind.Descriptor instead.
func (ScalarKind) EnumDescriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{0}
}

// Origin module of a type/enum/service.
// Carried inline on each declaration for direct access without lookups.
type ModuleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModulePath    string                 `protobuf:"bytes,1,opt,name=module_path,json=modulePath,proto3" json:"module_path,omitempty"` // "github.com/org/billing" from ogham.mod.yaml
	Package       string                 `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`                         // "billing" — ogham package name
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                         // "1.0.0"
	Generate      bool                   `protobuf:"varint,4,opt,name=generate,proto3" json:"generate,omitempty"`                      // true = own module, false = dependency
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleInfo) Reset() {
	*x = ModuleInfo{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleInfo) ProtoMessage() {}

func (x *ModuleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleInfo.ProtoReflect.Descriptor instead.
func (*ModuleInfo) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleInfo) GetModulePath() string {
	if x != nil {
		return x.ModulePath
	}
	return ""
}

func (x *ModuleInfo) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *ModuleInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModuleInfo) GetGenerate() bool {
	if x != nil {
		return x.Generate
	}
	return false
}

// Fully resolved module — the output of the compiler's AST → IR lowering.
// Everything is inline; plugins never need to resolve references.
type Module struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Types         []*Type                `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	Enums         []*Enum                `protobuf:"bytes,3,rep,name=enums,proto3" json:"enums,omitempty"`
	Services      []*Service             `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{1}
}

func (x *Module) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Module) GetTypes() []*Type {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *Module) GetEnums() []*Enum {
	if x != nil {
		return x.Enums
	}
	return nil
}

func (x *Module) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type Type struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FullName       string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"` // package-qualified: "example.User"
	Fields         []*Field               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Oneofs         []*OneofGroup          `protobuf:"bytes,4,rep,name=oneofs,proto3" json:"oneofs,omitempty"`
	NestedTypes    []*Type                `protobuf:"bytes,5,rep,name=nested_types,json=nestedTypes,proto3" json:"nested_types,omitempty"`
	NestedEnums    []*Enum                `protobuf:"bytes,6,rep,name=nested_enums,json=nestedEnums,proto3" json:"nested_enums,omitempty"`
	Annotations    []*AnnotationCall      `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty"`
	BackReferences []*TypeBackRef         `protobuf:"bytes,8,rep,name=back_references,json=backReferences,proto3" json:"back_references,omitempty"` // types that reference this type
	Trace          *TypeTrace             `protobuf:"bytes,9,opt,name=trace,proto3" json:"trace,omitempty"`                                         // origin trace
	Location       *common.SourceLocation `protobuf:"bytes,10,opt,name=location,proto3" json:"location,omitempty"`
	Module         *ModuleInfo            `protobuf:"bytes,16,opt,name=module,proto3" json:"module,omitempty"` // origin module of this type
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{2}
}

func (x *Type) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Type) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Type) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Type) GetOneofs() []*OneofGroup {
	if x != nil {
		return x.Oneofs
	}
	return nil
}

func (x *Type) GetNestedTypes() []*Type {
	if x != nil {
		return x.NestedTypes
	}
	return nil
}

func (x *Type) GetNestedEnums() []*Enum {
	if x != nil {
		return x.NestedEnums
	}
	return nil
}

func (x *Type) GetAnnotations() []*AnnotationCall {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Type) GetBackReferences() []*TypeBackRef {
	if x != nil {
		return x.BackReferences
	}
	return nil
}

func (x *Type) GetTrace() *TypeTrace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Type) GetLocation() *common.SourceLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Type) GetModule() *ModuleInfo {
	if x != nil {
		return x.Module
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number        uint32                 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Type          *TypeReference         `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // fully resolved, inline
	IsOptional    bool                   `protobuf:"varint,4,opt,name=is_optional,json=isOptional,proto3" json:"is_optional,omitempty"`
	IsRepeated    bool                   `protobuf:"varint,5,opt,name=is_repeated,json=isRepeated,proto3" json:"is_repeated,omitempty"`
	Annotations   []*AnnotationCall      `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty"`
	Mapping       *FieldMapping          `protobuf:"bytes,7,opt,name=mapping,proto3" json:"mapping,omitempty"` // projection source, if present
	Trace         *FieldTrace            `protobuf:"bytes,8,opt,name=trace,proto3" json:"trace,omitempty"`     // origin trace (shape, etc.)
	Location      *common.SourceLocation `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{3}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Field) GetType() *TypeReference {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Field) GetIsOptional() bool {
	if x != nil {
		return x.IsOptional
	}
	return false
}

func (x *Field) GetIsRepeated() bool {
	if x != nil {
		return x.IsRepeated
	}
	return false
}

func (x *Field) GetAnnotations() []*AnnotationCall {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Field) GetMapping() *FieldMapping {
	if x != nil {
		return x.Mapping
	}
	return nil
}

func (x *Field) GetTrace() *FieldTrace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Field) GetLocation() *common.SourceLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type OneofGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields        []*OneofField          `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	Annotations   []*AnnotationCall      `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty"`
	Location      *common.SourceLocation `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofGroup) Reset() {
	*x = OneofGroup{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofGroup) ProtoMessage() {}

func (x *OneofGroup) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofGroup.ProtoReflect.Descriptor instead.
func (*OneofGroup) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{4}
}

func (x *OneofGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OneofGroup) GetFields() []*OneofField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *OneofGroup) GetAnnotations() []*AnnotationCall {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *OneofGroup) GetLocation() *common.SourceLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type OneofField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number        uint32                 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Type          *TypeReference         `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Annotations   []*AnnotationCall      `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty"`
	Mapping       *FieldMapping          `protobuf:"bytes,5,opt,name=mapping,proto3" json:"mapping,omitempty"`
	Location      *common.SourceLocation `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofField) Reset() {
	*x = OneofField{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofField) ProtoMessage() {}

func (x *OneofField) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofField.ProtoReflect.Descriptor instead.
func (*OneofField) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{5}
}

func (x *OneofField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OneofField) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *OneofField) GetType() *TypeReference {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *OneofField) GetAnnotations() []*AnnotationCall {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *OneofField) GetMapping() *FieldMapping {
	if x != nil {
		return x.Mapping
	}
	return nil
}

func (x *OneofField) GetLocation() *common.SourceLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type Enum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Values        []*EnumValue           `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"` // includes implicit Unspecified=0
	Annotations   []*AnnotationCall      `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty"`
	Location      *common.SourceLocation `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Module        *ModuleInfo            `protobuf:"bytes,6,opt,name=module,proto3" json:"module,omitempty"` // origin module of this enum
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enum) Reset() {
	*x = Enum{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enum) ProtoMessage() {}

func (x *Enum) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enum.ProtoReflect.Descriptor instead.
func (*Enum) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{6}
}

func (x *Enum) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Enum) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Enum) GetValues() []*EnumValue {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Enum) GetAnnotations() []*AnnotationCall {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Enum) GetLocation() *common.SourceLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Enum) GetModule() *ModuleInfo {
	if x != nil {
		return x.Module
	}
	return nil
}

type EnumValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	IsRemoved     bool                   `protobuf:"varint,3,opt,name=is_removed,json=isRemoved,proto3" json:"is_removed,omitempty"`
	Fallback      string                 `protobuf:"bytes,4,opt,name=fallback,proto3" json:"fallback,omitempty"` // non-empty if is_removed
	Annotations   []*AnnotationCall      `protobuf:"bytes,5,rep,name=annotations,proto3" json:"annotations,omitempty"`
	Location      *common.SourceLocation `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValue) Reset() {
	*x = EnumValue{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValue) ProtoMessage() {}

func (x *EnumValue) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValue.ProtoReflect.Descriptor instead.
func (*EnumValue) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{7}
}

func (x *EnumValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnumValue) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *EnumValue) GetIsRemoved() bool {
	if x != nil {
		return x.IsRemoved
	}
	return false
}

func (x *EnumValue) GetFallback() string {
	if x != nil {
		return x.Fallback
	}
	return ""
}

func (x *EnumValue) GetAnnotations() []*AnnotationCall {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *EnumValue) GetLocation() *common.SourceLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Rpcs          []*Rpc                 `protobuf:"bytes,3,rep,name=rpcs,proto3" json:"rpcs,omitempty"`
	Annotations   []*AnnotationCall      `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty"`
	Location      *common.SourceLocation `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Module        *ModuleInfo            `protobuf:"bytes,6,opt,name=module,proto3" json:"module,omitempty"` // origin module of this service
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{8}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Service) GetRpcs() []*Rpc {
	if x != nil {
		return x.Rpcs
	}
	return nil
}

func (x *Service) GetAnnotations() []*AnnotationCall {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Service) GetLocation() *common.SourceLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Service) GetModule() *ModuleInfo {
	if x != nil {
		return x.Module
	}
	return nil
}

type Rpc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Input         *RpcParam              `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        *RpcParam              `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Annotations   []*AnnotationCall      `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty"`
	Location      *common.SourceLocation `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rpc) Reset() {
	*x = Rpc{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc) ProtoMessage() {}

func (x *Rpc) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc.ProtoReflect.Descriptor instead.
func (*Rpc) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{9}
}

func (x *Rpc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rpc) GetInput() *RpcParam {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Rpc) GetOutput() *RpcParam {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Rpc) GetAnnotations() []*AnnotationCall {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Rpc) GetLocation() *common.SourceLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type RpcParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsVoid        bool                   `protobuf:"varint,1,opt,name=is_void,json=isVoid,proto3" json:"is_void,omitempty"`
	IsStream      bool                   `protobuf:"varint,2,opt,name=is_stream,json=isStream,proto3" json:"is_stream,omitempty"`
	Type          *TypeReference         `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // resolved inline (monomorphized if generic)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcParam) Reset() {
	*x = RpcParam{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcParam) ProtoMessage() {}

func (x *RpcParam) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcParam.ProtoReflect.Descriptor instead.
func (*RpcParam) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{10}
}

func (x *RpcParam) GetIsVoid() bool {
	if x != nil {
		return x.IsVoid
	}
	return false
}

func (x *RpcParam) GetIsStream() bool {
	if x != nil {
		return x.IsStream
	}
	return false
}

func (x *RpcParam) GetType() *TypeReference {
	if x != nil {
		return x.Type
	}
	return nil
}

type TypeReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*TypeReference_Scalar
	//	*TypeReference_MessageType
	//	*TypeReference_EnumType
	//	*TypeReference_Map
	Kind          isTypeReference_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeReference) Reset() {
	*x = TypeReference{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeReference) ProtoMessage() {}

func (x *TypeReference) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeReference.ProtoReflect.Descriptor instead.
func (*TypeReference) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{11}
}

func (x *TypeReference) GetKind() isTypeReference_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *TypeReference) GetScalar() *ScalarType {
	if x != nil {
		if x, ok := x.Kind.(*TypeReference_Scalar); ok {
			return x.Scalar
		}
	}
	return nil
}

func (x *TypeReference) GetMessageType() *MessageType {
	if x != nil {
		if x, ok := x.Kind.(*TypeReference_MessageType); ok {
			return x.MessageType
		}
	}
	return nil
}

func (x *TypeReference) GetEnumType() *EnumType {
	if x != nil {
		if x, ok := x.Kind.(*TypeReference_EnumType); ok {
			return x.EnumType
		}
	}
	return nil
}

func (x *TypeReference) GetMap() *MapType {
	if x != nil {
		if x, ok := x.Kind.(*TypeReference_Map); ok {
			return x.Map
		}
	}
	return nil
}

type isTypeReference_Kind interface {
	isTypeReference_Kind()
}

type TypeReference_Scalar struct {
	Scalar *ScalarType `protobuf:"bytes,1,opt,name=scalar,proto3,oneof"`
}

type TypeReference_MessageType struct {
	MessageType *MessageType `protobuf:"bytes,2,opt,name=message_type,json=messageType,proto3,oneof"` // resolved inline — fields, annotations, etc.
}

type TypeReference_EnumType struct {
	EnumType *EnumType `protobuf:"bytes,3,opt,name=enum_type,json=enumType,proto3,oneof"` // resolved inline — all values
}

type TypeReference_Map struct {
	Map *MapType `protobuf:"bytes,4,opt,name=map,proto3,oneof"`
}

func (*TypeReference_Scalar) isTypeReference_Kind() {}

func (*TypeReference_MessageType) isTypeReference_Kind() {}

func (*TypeReference_EnumType) isTypeReference_Kind() {}

func (*TypeReference_Map) isTypeReference_Kind() {}

// Primitive/scalar type.
type ScalarType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScalarKind    ScalarKind             `protobuf:"varint,1,opt,name=scalar_kind,json=scalarKind,proto3,enum=oghamproto.ir.ScalarKind" json:"scalar_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalarType) Reset() {
	*x = ScalarType{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalarType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarType) ProtoMessage() {}

func (x *ScalarType) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarType.ProtoReflect.Descriptor instead.
func (*ScalarType) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{12}
}

func (x *ScalarType) GetScalarKind() ScalarKind {
	if x != nil {
		return x.ScalarKind
	}
	return ScalarKind_SCALAR_KIND_NONE
}

// Reference to a message type — carries the full type inline.
type MessageType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Fields        []*Field               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Oneofs        []*OneofGroup          `protobuf:"bytes,4,rep,name=oneofs,proto3" json:"oneofs,omitempty"`
	NestedEnums   []*Enum                `protobuf:"bytes,5,rep,name=nested_enums,json=nestedEnums,proto3" json:"nested_enums,omitempty"`
	Annotations   []*AnnotationCall      `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageType) Reset() {
	*x = MessageType{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageType) ProtoMessage() {}

func (x *MessageType) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageType.ProtoReflect.Descriptor instead.
func (*MessageType) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{13}
}

func (x *MessageType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MessageType) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *MessageType) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *MessageType) GetOneofs() []*OneofGroup {
	if x != nil {
		return x.Oneofs
	}
	return nil
}

func (x *MessageType) GetNestedEnums() []*Enum {
	if x != nil {
		return x.NestedEnums
	}
	return nil
}

func (x *MessageType) GetAnnotations() []*AnnotationCall {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// Reference to an enum type — carries all values inline.
type EnumType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Values        []*EnumValue           `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumType) Reset() {
	*x = EnumType{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumType) ProtoMessage() {}

func (x *EnumType) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumType.ProtoReflect.Descriptor instead.
func (*EnumType) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{14}
}

func (x *EnumType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnumType) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *EnumType) GetValues() []*EnumValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type MapType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *TypeReference         `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *TypeReference         `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapType) Reset() {
	*x = MapType{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapType) ProtoMessage() {}

func (x *MapType) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapType.ProtoReflect.Descriptor instead.
func (*MapType) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{15}
}

func (x *MapType) GetKey() *TypeReference {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MapType) GetValue() *TypeReference {
	if x != nil {
		return x.Value
	}
	return nil
}

type AnnotationCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Library       string                 `protobuf:"bytes,1,opt,name=library,proto3" json:"library,omitempty"` // "database", "validate", or "" for built-in
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`       // "Table", "Required", "default", etc.
	Arguments     []*AnnotationArgument  `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	Definition    *AnnotationDefinition  `protobuf:"bytes,4,opt,name=definition,proto3" json:"definition,omitempty"` // full definition inline
	Location      *common.SourceLocation `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationCall) Reset() {
	*x = AnnotationCall{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationCall) ProtoMessage() {}

func (x *AnnotationCall) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationCall.ProtoReflect.Descriptor instead.
func (*AnnotationCall) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{16}
}

func (x *AnnotationCall) GetLibrary() string {
	if x != nil {
		return x.Library
	}
	return ""
}

func (x *AnnotationCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnnotationCall) GetArguments() []*AnnotationArgument {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *AnnotationCall) GetDefinition() *AnnotationDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *AnnotationCall) GetLocation() *common.SourceLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type AnnotationArgument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         *AnnotationLiteral     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationArgument) Reset() {
	*x = AnnotationArgument{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationArgument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationArgument) ProtoMessage() {}

func (x *AnnotationArgument) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationArgument.ProtoReflect.Descriptor instead.
func (*AnnotationArgument) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{17}
}

func (x *AnnotationArgument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnnotationArgument) GetValue() *AnnotationLiteral {
	if x != nil {
		return x.Value
	}
	return nil
}

type AnnotationLiteral struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*AnnotationLiteral_StringValue
	//	*AnnotationLiteral_IntValue
	//	*AnnotationLiteral_FloatValue
	//	*AnnotationLiteral_BoolValue
	//	*AnnotationLiteral_StructValue
	//	*AnnotationLiteral_ListValue
	Value         isAnnotationLiteral_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationLiteral) Reset() {
	*x = AnnotationLiteral{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationLiteral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationLiteral) ProtoMessage() {}

func (x *AnnotationLiteral) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationLiteral.ProtoReflect.Descriptor instead.
func (*AnnotationLiteral) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{18}
}

func (x *AnnotationLiteral) GetValue() isAnnotationLiteral_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AnnotationLiteral) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*AnnotationLiteral_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *AnnotationLiteral) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*AnnotationLiteral_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *AnnotationLiteral) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*AnnotationLiteral_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *AnnotationLiteral) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*AnnotationLiteral_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *AnnotationLiteral) GetStructValue() *AnnotationStruct {
	if x != nil {
		if x, ok := x.Value.(*AnnotationLiteral_StructValue); ok {
			return x.StructValue
		}
	}
	return nil
}

func (x *AnnotationLiteral) GetListValue() *AnnotationList {
	if x != nil {
		if x, ok := x.Value.(*AnnotationLiteral_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

type isAnnotationLiteral_Value interface {
	isAnnotationLiteral_Value()
}

type AnnotationLiteral_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type AnnotationLiteral_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type AnnotationLiteral_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,3,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type AnnotationLiteral_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type AnnotationLiteral_StructValue struct {
	StructValue *AnnotationStruct `protobuf:"bytes,5,opt,name=struct_value,json=structValue,proto3,oneof"`
}

type AnnotationLiteral_ListValue struct {
	ListValue *AnnotationList `protobuf:"bytes,6,opt,name=list_value,json=listValue,proto3,oneof"`
}

func (*AnnotationLiteral_StringValue) isAnnotationLiteral_Value() {}

func (*AnnotationLiteral_IntValue) isAnnotationLiteral_Value() {}

func (*AnnotationLiteral_FloatValue) isAnnotationLiteral_Value() {}

func (*AnnotationLiteral_BoolValue) isAnnotationLiteral_Value() {}

func (*AnnotationLiteral_StructValue) isAnnotationLiteral_Value() {}

func (*AnnotationLiteral_ListValue) isAnnotationLiteral_Value() {}

type AnnotationStruct struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Fields        map[string]*AnnotationLiteral `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationStruct) Reset() {
	*x = AnnotationStruct{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationStruct) ProtoMessage() {}

func (x *AnnotationStruct) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationStruct.ProtoReflect.Descriptor instead.
func (*AnnotationStruct) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{19}
}

func (x *AnnotationStruct) GetFields() map[string]*AnnotationLiteral {
	if x != nil {
		return x.Fields
	}
	return nil
}

type AnnotationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*AnnotationLiteral   `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationList) Reset() {
	*x = AnnotationList{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationList) ProtoMessage() {}

func (x *AnnotationList) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationList.ProtoReflect.Descriptor instead.
func (*AnnotationList) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{20}
}

func (x *AnnotationList) GetValues() []*AnnotationLiteral {
	if x != nil {
		return x.Values
	}
	return nil
}

// Full annotation definition (schema).
type AnnotationDefinition struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Library       string                      `protobuf:"bytes,1,opt,name=library,proto3" json:"library,omitempty"`
	Name          string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Targets       []string                    `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"` // "type", "field", "enum", etc.
	Parameters    []*AnnotationParameter      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty"`
	Compositions  []*AnnotationCompositionRef `protobuf:"bytes,5,rep,name=compositions,proto3" json:"compositions,omitempty"` // included annotations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationDefinition) Reset() {
	*x = AnnotationDefinition{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationDefinition) ProtoMessage() {}

func (x *AnnotationDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationDefinition.ProtoReflect.Descriptor instead.
func (*AnnotationDefinition) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{21}
}

func (x *AnnotationDefinition) GetLibrary() string {
	if x != nil {
		return x.Library
	}
	return ""
}

func (x *AnnotationDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnnotationDefinition) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *AnnotationDefinition) GetParameters() []*AnnotationParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *AnnotationDefinition) GetCompositions() []*AnnotationCompositionRef {
	if x != nil {
		return x.Compositions
	}
	return nil
}

type AnnotationParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          *TypeReference         `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	IsOptional    bool                   `protobuf:"varint,3,opt,name=is_optional,json=isOptional,proto3" json:"is_optional,omitempty"`
	DefaultValue  *AnnotationLiteral     `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"` // present if has default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationParameter) Reset() {
	*x = AnnotationParameter{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationParameter) ProtoMessage() {}

func (x *AnnotationParameter) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationParameter.ProtoReflect.Descriptor instead.
func (*AnnotationParameter) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{22}
}

func (x *AnnotationParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnnotationParameter) GetType() *TypeReference {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *AnnotationParameter) GetIsOptional() bool {
	if x != nil {
		return x.IsOptional
	}
	return false
}

func (x *AnnotationParameter) GetDefaultValue() *AnnotationLiteral {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

// Reference to a composed annotation.
type AnnotationCompositionRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Library       string                 `protobuf:"bytes,1,opt,name=library,proto3" json:"library,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     []*AnnotationArgument  `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationCompositionRef) Reset() {
	*x = AnnotationCompositionRef{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationCompositionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationCompositionRef) ProtoMessage() {}

func (x *AnnotationCompositionRef) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationCompositionRef.ProtoReflect.Descriptor instead.
func (*AnnotationCompositionRef) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{23}
}

func (x *AnnotationCompositionRef) GetLibrary() string {
	if x != nil {
		return x.Library
	}
	return ""
}

func (x *AnnotationCompositionRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnnotationCompositionRef) GetArguments() []*AnnotationArgument {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// Source mapping for a projected field.
type FieldMapping struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full chain from immediate source to root.
	// Example: UserCard.name <- UserResponse.name <- User.first_name
	// chain[0] = immediate source, chain[last] = root source.
	Chain         []*MappingLink `protobuf:"bytes,1,rep,name=chain,proto3" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldMapping) Reset() {
	*x = FieldMapping{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldMapping) ProtoMessage() {}

func (x *FieldMapping) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldMapping.ProtoReflect.Descriptor instead.
func (*FieldMapping) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{24}
}

func (x *FieldMapping) GetChain() []*MappingLink {
	if x != nil {
		return x.Chain
	}
	return nil
}

// One link in a projection chain.
type MappingLink struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SourceTypeName         string                 `protobuf:"bytes,1,opt,name=source_type_name,json=sourceTypeName,proto3" json:"source_type_name,omitempty"`                         // "User"
	SourceTypeFullName     string                 `protobuf:"bytes,2,opt,name=source_type_full_name,json=sourceTypeFullName,proto3" json:"source_type_full_name,omitempty"`           // "example.User"
	SourceFieldName        string                 `protobuf:"bytes,3,opt,name=source_field_name,json=sourceFieldName,proto3" json:"source_field_name,omitempty"`                      // "first_name"
	Path                   []string               `protobuf:"bytes,4,rep,name=path,proto3" json:"path,omitempty"`                                                                     // for nested: ["billing", "street"] or ["method", "*", "tx_id"]
	SourceFieldType        *TypeReference         `protobuf:"bytes,5,opt,name=source_field_type,json=sourceFieldType,proto3" json:"source_field_type,omitempty"`                      // inline
	SourceFieldAnnotations []*AnnotationCall      `protobuf:"bytes,6,rep,name=source_field_annotations,json=sourceFieldAnnotations,proto3" json:"source_field_annotations,omitempty"` // inline
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MappingLink) Reset() {
	*x = MappingLink{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappingLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingLink) ProtoMessage() {}

func (x *MappingLink) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingLink.ProtoReflect.Descriptor instead.
func (*MappingLink) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{25}
}

func (x *MappingLink) GetSourceTypeName() string {
	if x != nil {
		return x.SourceTypeName
	}
	return ""
}

func (x *MappingLink) GetSourceTypeFullName() string {
	if x != nil {
		return x.SourceTypeFullName
	}
	return ""
}

func (x *MappingLink) GetSourceFieldName() string {
	if x != nil {
		return x.SourceFieldName
	}
	return ""
}

func (x *MappingLink) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *MappingLink) GetSourceFieldType() *TypeReference {
	if x != nil {
		return x.SourceFieldType
	}
	return nil
}

func (x *MappingLink) GetSourceFieldAnnotations() []*AnnotationCall {
	if x != nil {
		return x.SourceFieldAnnotations
	}
	return nil
}

// Trace on a Type: where did this type come from?
type TypeTrace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Origin:
	//
	//	*TypeTrace_Generic
	//	*TypeTrace_PickOmit
	Origin        isTypeTrace_Origin `protobuf_oneof:"origin"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeTrace) Reset() {
	*x = TypeTrace{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeTrace) ProtoMessage() {}

func (x *TypeTrace) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeTrace.ProtoReflect.Descriptor instead.
func (*TypeTrace) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{26}
}

func (x *TypeTrace) GetOrigin() isTypeTrace_Origin {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *TypeTrace) GetGeneric() *GenericOrigin {
	if x != nil {
		if x, ok := x.Origin.(*TypeTrace_Generic); ok {
			return x.Generic
		}
	}
	return nil
}

func (x *TypeTrace) GetPickOmit() *PickOmitOrigin {
	if x != nil {
		if x, ok := x.Origin.(*TypeTrace_PickOmit); ok {
			return x.PickOmit
		}
	}
	return nil
}

type isTypeTrace_Origin interface {
	isTypeTrace_Origin()
}

type TypeTrace_Generic struct {
	Generic *GenericOrigin `protobuf:"bytes,1,opt,name=generic,proto3,oneof"` // monomorphized from a generic
}

type TypeTrace_PickOmit struct {
	PickOmit *PickOmitOrigin `protobuf:"bytes,2,opt,name=pick_omit,json=pickOmit,proto3,oneof"` // created via Pick/Omit
}

func (*TypeTrace_Generic) isTypeTrace_Origin() {}

func (*TypeTrace_PickOmit) isTypeTrace_Origin() {}

type GenericOrigin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceName    string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`          // "Paginated"
	TypeArguments []string               `protobuf:"bytes,2,rep,name=type_arguments,json=typeArguments,proto3" json:"type_arguments,omitempty"` // ["User"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericOrigin) Reset() {
	*x = GenericOrigin{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericOrigin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericOrigin) ProtoMessage() {}

func (x *GenericOrigin) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericOrigin.ProtoReflect.Descriptor instead.
func (*GenericOrigin) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{27}
}

func (x *GenericOrigin) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *GenericOrigin) GetTypeArguments() []string {
	if x != nil {
		return x.TypeArguments
	}
	return nil
}

type PickOmitOrigin struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`                                             // "Pick" or "Omit"
	SourceTypeName string                 `protobuf:"bytes,2,opt,name=source_type_name,json=sourceTypeName,proto3" json:"source_type_name,omitempty"` // "User"
	FieldNames     []string               `protobuf:"bytes,3,rep,name=field_names,json=fieldNames,proto3" json:"field_names,omitempty"`               // fields picked/omitted
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PickOmitOrigin) Reset() {
	*x = PickOmitOrigin{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickOmitOrigin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickOmitOrigin) ProtoMessage() {}

func (x *PickOmitOrigin) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickOmitOrigin.ProtoReflect.Descriptor instead.
func (*PickOmitOrigin) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{28}
}

func (x *PickOmitOrigin) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PickOmitOrigin) GetSourceTypeName() string {
	if x != nil {
		return x.SourceTypeName
	}
	return ""
}

func (x *PickOmitOrigin) GetFieldNames() []string {
	if x != nil {
		return x.FieldNames
	}
	return nil
}

// Trace on a Field: where did this field come from?
type FieldTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shape         *ShapeOrigin           `protobuf:"bytes,1,opt,name=shape,proto3" json:"shape,omitempty"` // non-null if field came from a shape injection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldTrace) Reset() {
	*x = FieldTrace{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldTrace) ProtoMessage() {}

func (x *FieldTrace) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldTrace.ProtoReflect.Descriptor instead.
func (*FieldTrace) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{29}
}

func (x *FieldTrace) GetShape() *ShapeOrigin {
	if x != nil {
		return x.Shape
	}
	return nil
}

type ShapeOrigin struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ShapeName           string                 `protobuf:"bytes,1,opt,name=shape_name,json=shapeName,proto3" json:"shape_name,omitempty"`               // "Timestamps"
	ShapeFullName       string                 `protobuf:"bytes,2,opt,name=shape_full_name,json=shapeFullName,proto3" json:"shape_full_name,omitempty"` // "example.Timestamps"
	InjectionRangeStart uint32                 `protobuf:"varint,3,opt,name=injection_range_start,json=injectionRangeStart,proto3" json:"injection_range_start,omitempty"`
	InjectionRangeEnd   uint32                 `protobuf:"varint,4,opt,name=injection_range_end,json=injectionRangeEnd,proto3" json:"injection_range_end,omitempty"`
	ShapeLocation       *common.SourceLocation `protobuf:"bytes,5,opt,name=shape_location,json=shapeLocation,proto3" json:"shape_location,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ShapeOrigin) Reset() {
	*x = ShapeOrigin{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShapeOrigin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShapeOrigin) ProtoMessage() {}

func (x *ShapeOrigin) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShapeOrigin.ProtoReflect.Descriptor instead.
func (*ShapeOrigin) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{30}
}

func (x *ShapeOrigin) GetShapeName() string {
	if x != nil {
		return x.ShapeName
	}
	return ""
}

func (x *ShapeOrigin) GetShapeFullName() string {
	if x != nil {
		return x.ShapeFullName
	}
	return ""
}

func (x *ShapeOrigin) GetInjectionRangeStart() uint32 {
	if x != nil {
		return x.InjectionRangeStart
	}
	return 0
}

func (x *ShapeOrigin) GetInjectionRangeEnd() uint32 {
	if x != nil {
		return x.InjectionRangeEnd
	}
	return 0
}

func (x *ShapeOrigin) GetShapeLocation() *common.SourceLocation {
	if x != nil {
		return x.ShapeLocation
	}
	return nil
}

// A reference from another type to this type.
type TypeBackRef struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ReferencingTypeName     string                 `protobuf:"bytes,1,opt,name=referencing_type_name,json=referencingTypeName,proto3" json:"referencing_type_name,omitempty"`
	ReferencingTypeFullName string                 `protobuf:"bytes,2,opt,name=referencing_type_full_name,json=referencingTypeFullName,proto3" json:"referencing_type_full_name,omitempty"`
	FieldName               string                 `protobuf:"bytes,3,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"` // the field that holds the reference
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TypeBackRef) Reset() {
	*x = TypeBackRef{}
	mi := &file_oghamproto_ir_types_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeBackRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeBackRef) ProtoMessage() {}

func (x *TypeBackRef) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_ir_types_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeBackRef.ProtoReflect.Descriptor instead.
func (*TypeBackRef) Descriptor() ([]byte, []int) {
	return file_oghamproto_ir_types_proto_rawDescGZIP(), []int{31}
}

func (x *TypeBackRef) GetReferencingTypeName() string {
	if x != nil {
		return x.ReferencingTypeName
	}
	return ""
}

func (x *TypeBackRef) GetReferencingTypeFullName() string {
	if x != nil {
		return x.ReferencingTypeFullName
	}
	return ""
}

func (x *TypeBackRef) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

var File_oghamproto_ir_types_proto protoreflect.FileDescriptor

const file_oghamproto_ir_types_proto_rawDesc = "" +
	"\n" +
	"\x19oghamproto/ir/types.proto\x12\roghamproto.ir\x1a\x1eoghamproto/common/source.proto\"}\n" +
	"\n" +
	"ModuleInfo\x12\x1f\n" +
	"\vmodule_path\x18\x01 \x01(\tR\n" +
	"modulePath\x12\x18\n" +
	"\apackage\x18\x02 \x01(\tR\apackage\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bgenerate\x18\x04 \x01(\bR\bgenerate\"\xac\x01\n" +
	"\x06Module\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12)\n" +
	"\x05types\x18\x02 \x03(\v2\x13.oghamproto.ir.TypeR\x05types\x12)\n" +
	"\x05enums\x18\x03 \x03(\v2\x13.oghamproto.ir.EnumR\x05enums\x122\n" +
	"\bservices\x18\x04 \x03(\v2\x16.oghamproto.ir.ServiceR\bservices\"\xb0\x04\n" +
	"\x04Type\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12,\n" +
	"\x06fields\x18\x03 \x03(\v2\x14.oghamproto.ir.FieldR\x06fields\x121\n" +
	"\x06oneofs\x18\x04 \x03(\v2\x19.oghamproto.ir.OneofGroupR\x06oneofs\x126\n" +
	"\fnested_types\x18\x05 \x03(\v2\x13.oghamproto.ir.TypeR\vnestedTypes\x126\n" +
	"\fnested_enums\x18\x06 \x03(\v2\x13.oghamproto.ir.EnumR\vnestedEnums\x12?\n" +
	"\vannotations\x18\a \x03(\v2\x1d.oghamproto.ir.AnnotationCallR\vannotations\x12C\n" +
	"\x0fback_references\x18\b \x03(\v2\x1a.oghamproto.ir.TypeBackRefR\x0ebackReferences\x12.\n" +
	"\x05trace\x18\t \x01(\v2\x18.oghamproto.ir.TypeTraceR\x05trace\x12=\n" +
	"\blocation\x18\n" +
	" \x01(\v2!.oghamproto.common.SourceLocationR\blocation\x121\n" +
	"\x06module\x18\x10 \x01(\v2\x19.oghamproto.ir.ModuleInfoR\x06module\"\x8f\x03\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\x02 \x01(\rR\x06number\x120\n" +
	"\x04type\x18\x03 \x01(\v2\x1c.oghamproto.ir.TypeReferenceR\x04type\x12\x1f\n" +
	"\vis_optional\x18\x04 \x01(\bR\n" +
	"isOptional\x12\x1f\n" +
	"\vis_repeated\x18\x05 \x01(\bR\n" +
	"isRepeated\x12?\n" +
	"\vannotations\x18\x06 \x03(\v2\x1d.oghamproto.ir.AnnotationCallR\vannotations\x125\n" +
	"\amapping\x18\a \x01(\v2\x1b.oghamproto.ir.FieldMappingR\amapping\x12/\n" +
	"\x05trace\x18\b \x01(\v2\x19.oghamproto.ir.FieldTraceR\x05trace\x12=\n" +
	"\blocation\x18\t \x01(\v2!.oghamproto.common.SourceLocationR\blocation\"\xd3\x01\n" +
	"\n" +
	"OneofGroup\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x06fields\x18\x02 \x03(\v2\x19.oghamproto.ir.OneofFieldR\x06fields\x12?\n" +
	"\vannotations\x18\x03 \x03(\v2\x1d.oghamproto.ir.AnnotationCallR\vannotations\x12=\n" +
	"\blocation\x18\x04 \x01(\v2!.oghamproto.common.SourceLocationR\blocation\"\xa1\x02\n" +
	"\n" +
	"OneofField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\x02 \x01(\rR\x06number\x120\n" +
	"\x04type\x18\x03 \x01(\v2\x1c.oghamproto.ir.TypeReferenceR\x04type\x12?\n" +
	"\vannotations\x18\x04 \x03(\v2\x1d.oghamproto.ir.AnnotationCallR\vannotations\x125\n" +
	"\amapping\x18\x05 \x01(\v2\x1b.oghamproto.ir.FieldMappingR\amapping\x12=\n" +
	"\blocation\x18\x06 \x01(\v2!.oghamproto.common.SourceLocationR\blocation\"\x9c\x02\n" +
	"\x04Enum\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x120\n" +
	"\x06values\x18\x03 \x03(\v2\x18.oghamproto.ir.EnumValueR\x06values\x12?\n" +
	"\vannotations\x18\x04 \x03(\v2\x1d.oghamproto.ir.AnnotationCallR\vannotations\x12=\n" +
	"\blocation\x18\x05 \x01(\v2!.oghamproto.common.SourceLocationR\blocation\x121\n" +
	"\x06module\x18\x06 \x01(\v2\x19.oghamproto.ir.ModuleInfoR\x06module\"\xf2\x01\n" +
	"\tEnumValue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x1d\n" +
	"\n" +
	"is_removed\x18\x03 \x01(\bR\tisRemoved\x12\x1a\n" +
	"\bfallback\x18\x04 \x01(\tR\bfallback\x12?\n" +
	"\vannotations\x18\x05 \x03(\v2\x1d.oghamproto.ir.AnnotationCallR\vannotations\x12=\n" +
	"\blocation\x18\x06 \x01(\v2!.oghamproto.common.SourceLocationR\blocation\"\x95\x02\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12&\n" +
	"\x04rpcs\x18\x03 \x03(\v2\x12.oghamproto.ir.RpcR\x04rpcs\x12?\n" +
	"\vannotations\x18\x04 \x03(\v2\x1d.oghamproto.ir.AnnotationCallR\vannotations\x12=\n" +
	"\blocation\x18\x05 \x01(\v2!.oghamproto.common.SourceLocationR\blocation\x121\n" +
	"\x06module\x18\x06 \x01(\v2\x19.oghamproto.ir.ModuleInfoR\x06module\"\xf9\x01\n" +
	"\x03Rpc\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x05input\x18\x02 \x01(\v2\x17.oghamproto.ir.RpcParamR\x05input\x12/\n" +
	"\x06output\x18\x03 \x01(\v2\x17.oghamproto.ir.RpcParamR\x06output\x12?\n" +
	"\vannotations\x18\x04 \x03(\v2\x1d.oghamproto.ir.AnnotationCallR\vannotations\x12=\n" +
	"\blocation\x18\x05 \x01(\v2!.oghamproto.common.SourceLocationR\blocation\"r\n" +
	"\bRpcParam\x12\x17\n" +
	"\ais_void\x18\x01 \x01(\bR\x06isVoid\x12\x1b\n" +
	"\tis_stream\x18\x02 \x01(\bR\bisStream\x120\n" +
	"\x04type\x18\x03 \x01(\v2\x1c.oghamproto.ir.TypeReferenceR\x04type\"\xf1\x01\n" +
	"\rTypeReference\x123\n" +
	"\x06scalar\x18\x01 \x01(\v2\x19.oghamproto.ir.ScalarTypeH\x00R\x06scalar\x12?\n" +
	"\fmessage_type\x18\x02 \x01(\v2\x1a.oghamproto.ir.MessageTypeH\x00R\vmessageType\x126\n" +
	"\tenum_type\x18\x03 \x01(\v2\x17.oghamproto.ir.EnumTypeH\x00R\benumType\x12*\n" +
	"\x03map\x18\x04 \x01(\v2\x16.oghamproto.ir.MapTypeH\x00R\x03mapB\x06\n" +
	"\x04kind\"H\n" +
	"\n" +
	"ScalarType\x12:\n" +
	"\vscalar_kind\x18\x01 \x01(\x0e2\x19.oghamproto.ir.ScalarKindR\n" +
	"scalarKind\"\x98\x02\n" +
	"\vMessageType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12,\n" +
	"\x06fields\x18\x03 \x03(\v2\x14.oghamproto.ir.FieldR\x06fields\x121\n" +
	"\x06oneofs\x18\x04 \x03(\v2\x19.oghamproto.ir.OneofGroupR\x06oneofs\x126\n" +
	"\fnested_enums\x18\x05 \x03(\v2\x13.oghamproto.ir.EnumR\vnestedEnums\x12?\n" +
	"\vannotations\x18\x06 \x03(\v2\x1d.oghamproto.ir.AnnotationCallR\vannotations\"m\n" +
	"\bEnumType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x120\n" +
	"\x06values\x18\x03 \x03(\v2\x18.oghamproto.ir.EnumValueR\x06values\"m\n" +
	"\aMapType\x12.\n" +
	"\x03key\x18\x01 \x01(\v2\x1c.oghamproto.ir.TypeReferenceR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.oghamproto.ir.TypeReferenceR\x05value\"\x83\x02\n" +
	"\x0eAnnotationCall\x12\x18\n" +
	"\alibrary\x18\x01 \x01(\tR\alibrary\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12?\n" +
	"\targuments\x18\x03 \x03(\v2!.oghamproto.ir.AnnotationArgumentR\targuments\x12C\n" +
	"\n" +
	"definition\x18\x04 \x01(\v2#.oghamproto.ir.AnnotationDefinitionR\n" +
	"definition\x12=\n" +
	"\blocation\x18\x05 \x01(\v2!.oghamproto.common.SourceLocationR\blocation\"`\n" +
	"\x12AnnotationArgument\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .oghamproto.ir.AnnotationLiteralR\x05value\"\xaa\x02\n" +
	"\x11AnnotationLiteral\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\x03 \x01(\x01H\x00R\n" +
	"floatValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12D\n" +
	"\fstruct_value\x18\x05 \x01(\v2\x1f.oghamproto.ir.AnnotationStructH\x00R\vstructValue\x12>\n" +
	"\n" +
	"list_value\x18\x06 \x01(\v2\x1d.oghamproto.ir.AnnotationListH\x00R\tlistValueB\a\n" +
	"\x05value\"\xb4\x01\n" +
	"\x10AnnotationStruct\x12C\n" +
	"\x06fields\x18\x01 \x03(\v2+.oghamproto.ir.AnnotationStruct.FieldsEntryR\x06fields\x1a[\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .oghamproto.ir.AnnotationLiteralR\x05value:\x028\x01\"J\n" +
	"\x0eAnnotationList\x128\n" +
	"\x06values\x18\x01 \x03(\v2 .oghamproto.ir.AnnotationLiteralR\x06values\"\xef\x01\n" +
	"\x14AnnotationDefinition\x12\x18\n" +
	"\alibrary\x18\x01 \x01(\tR\alibrary\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\atargets\x18\x03 \x03(\tR\atargets\x12B\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2\".oghamproto.ir.AnnotationParameterR\n" +
	"parameters\x12K\n" +
	"\fcompositions\x18\x05 \x03(\v2'.oghamproto.ir.AnnotationCompositionRefR\fcompositions\"\xc3\x01\n" +
	"\x13AnnotationParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x04type\x18\x02 \x01(\v2\x1c.oghamproto.ir.TypeReferenceR\x04type\x12\x1f\n" +
	"\vis_optional\x18\x03 \x01(\bR\n" +
	"isOptional\x12E\n" +
	"\rdefault_value\x18\x04 \x01(\v2 .oghamproto.ir.AnnotationLiteralR\fdefaultValue\"\x89\x01\n" +
	"\x18AnnotationCompositionRef\x12\x18\n" +
	"\alibrary\x18\x01 \x01(\tR\alibrary\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12?\n" +
	"\targuments\x18\x03 \x03(\v2!.oghamproto.ir.AnnotationArgumentR\targuments\"@\n" +
	"\fFieldMapping\x120\n" +
	"\x05chain\x18\x01 \x03(\v2\x1a.oghamproto.ir.MappingLinkR\x05chain\"\xcd\x02\n" +
	"\vMappingLink\x12(\n" +
	"\x10source_type_name\x18\x01 \x01(\tR\x0esourceTypeName\x121\n" +
	"\x15source_type_full_name\x18\x02 \x01(\tR\x12sourceTypeFullName\x12*\n" +
	"\x11source_field_name\x18\x03 \x01(\tR\x0fsourceFieldName\x12\x12\n" +
	"\x04path\x18\x04 \x03(\tR\x04path\x12H\n" +
	"\x11source_field_type\x18\x05 \x01(\v2\x1c.oghamproto.ir.TypeReferenceR\x0fsourceFieldType\x12W\n" +
	"\x18source_field_annotations\x18\x06 \x03(\v2\x1d.oghamproto.ir.AnnotationCallR\x16sourceFieldAnnotations\"\x8d\x01\n" +
	"\tTypeTrace\x128\n" +
	"\ageneric\x18\x01 \x01(\v2\x1c.oghamproto.ir.GenericOriginH\x00R\ageneric\x12<\n" +
	"\tpick_omit\x18\x02 \x01(\v2\x1d.oghamproto.ir.PickOmitOriginH\x00R\bpickOmitB\b\n" +
	"\x06origin\"W\n" +
	"\rGenericOrigin\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12%\n" +
	"\x0etype_arguments\x18\x02 \x03(\tR\rtypeArguments\"o\n" +
	"\x0ePickOmitOrigin\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12(\n" +
	"\x10source_type_name\x18\x02 \x01(\tR\x0esourceTypeName\x12\x1f\n" +
	"\vfield_names\x18\x03 \x03(\tR\n" +
	"fieldNames\">\n" +
	"\n" +
	"FieldTrace\x120\n" +
	"\x05shape\x18\x01 \x01(\v2\x1a.oghamproto.ir.ShapeOriginR\x05shape\"\x82\x02\n" +
	"\vShapeOrigin\x12\x1d\n" +
	"\n" +
	"shape_name\x18\x01 \x01(\tR\tshapeName\x12&\n" +
	"\x0fshape_full_name\x18\x02 \x01(\tR\rshapeFullName\x122\n" +
	"\x15injection_range_start\x18\x03 \x01(\rR\x13injectionRangeStart\x12.\n" +
	"\x13injection_range_end\x18\x04 \x01(\rR\x11injectionRangeEnd\x12H\n" +
	"\x0eshape_location\x18\x05 \x01(\v2!.oghamproto.common.SourceLocationR\rshapeLocation\"\x9d\x01\n" +
	"\vTypeBackRef\x122\n" +
	"\x15referencing_type_name\x18\x01 \x01(\tR\x13referencingTypeName\x12;\n" +
	"\x1areferencing_type_full_name\x18\x02 \x01(\tR\x17referencingTypeFullName\x12\x1d\n" +
	"\n" +
	"field_name\x18\x03 \x01(\tR\tfieldName*\xb4\x01\n" +
	"\n" +
	"ScalarKind\x12\x14\n" +
	"\x10SCALAR_KIND_NONE\x10\x00\x12\b\n" +
	"\x04BOOL\x10\x01\x12\n" +
	"\n" +
	"\x06STRING\x10\x02\x12\t\n" +
	"\x05BYTES\x10\x03\x12\b\n" +
	"\x04INT8\x10\x04\x12\t\n" +
	"\x05INT16\x10\x05\x12\t\n" +
	"\x05INT32\x10\x06\x12\t\n" +
	"\x05INT64\x10\a\x12\t\n" +
	"\x05UINT8\x10\b\x12\n" +
	"\n" +
	"\x06UINT16\x10\t\x12\n" +
	"\n" +
	"\x06UINT32\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06UINT64\x10\v\x12\t\n" +
	"\x05FLOAT\x10\f\x12\n" +
	"\n" +
	"\x06DOUBLE\x10\rB'Z%github.com/oghamlang/go/oghamproto/irb\x06proto3"

var (
	file_oghamproto_ir_types_proto_rawDescOnce sync.Once
	file_oghamproto_ir_types_proto_rawDescData []byte
)

func file_oghamproto_ir_types_proto_rawDescGZIP() []byte {
	file_oghamproto_ir_types_proto_rawDescOnce.Do(func() {
		file_oghamproto_ir_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oghamproto_ir_types_proto_rawDesc), len(file_oghamproto_ir_types_proto_rawDesc)))
	})
	return file_oghamproto_ir_types_proto_rawDescData
}

var file_oghamproto_ir_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_oghamproto_ir_types_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_oghamproto_ir_types_proto_goTypes = []any{
	(ScalarKind)(0),                  // 0: oghamproto.ir.ScalarKind
	(*ModuleInfo)(nil),               // 1: oghamproto.ir.ModuleInfo
	(*Module)(nil),                   // 2: oghamproto.ir.Module
	(*Type)(nil),                     // 3: oghamproto.ir.Type
	(*Field)(nil),                    // 4: oghamproto.ir.Field
	(*OneofGroup)(nil),               // 5: oghamproto.ir.OneofGroup
	(*OneofField)(nil),               // 6: oghamproto.ir.OneofField
	(*Enum)(nil),                     // 7: oghamproto.ir.Enum
	(*EnumValue)(nil),                // 8: oghamproto.ir.EnumValue
	(*Service)(nil),                  // 9: oghamproto.ir.Service
	(*Rpc)(nil),                      // 10: oghamproto.ir.Rpc
	(*RpcParam)(nil),                 // 11: oghamproto.ir.RpcParam
	(*TypeReference)(nil),            // 12: oghamproto.ir.TypeReference
	(*ScalarType)(nil),               // 13: oghamproto.ir.ScalarType
	(*MessageType)(nil),              // 14: oghamproto.ir.MessageType
	(*EnumType)(nil),                 // 15: oghamproto.ir.EnumType
	(*MapType)(nil),                  // 16: oghamproto.ir.MapType
	(*AnnotationCall)(nil),           // 17: oghamproto.ir.AnnotationCall
	(*AnnotationArgument)(nil),       // 18: oghamproto.ir.AnnotationArgument
	(*AnnotationLiteral)(nil),        // 19: oghamproto.ir.AnnotationLiteral
	(*AnnotationStruct)(nil),         // 20: oghamproto.ir.AnnotationStruct
	(*AnnotationList)(nil),           // 21: oghamproto.ir.AnnotationList
	(*AnnotationDefinition)(nil),     // 22: oghamproto.ir.AnnotationDefinition
	(*AnnotationParameter)(nil),      // 23: oghamproto.ir.AnnotationParameter
	(*AnnotationCompositionRef)(nil), // 24: oghamproto.ir.AnnotationCompositionRef
	(*FieldMapping)(nil),             // 25: oghamproto.ir.FieldMapping
	(*MappingLink)(nil),              // 26: oghamproto.ir.MappingLink
	(*TypeTrace)(nil),                // 27: oghamproto.ir.TypeTrace
	(*GenericOrigin)(nil),            // 28: oghamproto.ir.GenericOrigin
	(*PickOmitOrigin)(nil),           // 29: oghamproto.ir.PickOmitOrigin
	(*FieldTrace)(nil),               // 30: oghamproto.ir.FieldTrace
	(*ShapeOrigin)(nil),              // 31: oghamproto.ir.ShapeOrigin
	(*TypeBackRef)(nil),              // 32: oghamproto.ir.TypeBackRef
	nil,                              // 33: oghamproto.ir.AnnotationStruct.FieldsEntry
	(*common.SourceLocation)(nil),    // 34: oghamproto.common.SourceLocation
}
var file_oghamproto_ir_types_proto_depIdxs = []int32{
	3,  // 0: oghamproto.ir.Module.types:type_name -> oghamproto.ir.Type
	7,  // 1: oghamproto.ir.Module.enums:type_name -> oghamproto.ir.Enum
	9,  // 2: oghamproto.ir.Module.services:type_name -> oghamproto.ir.Service
	4,  // 3: oghamproto.ir.Type.fields:type_name -> oghamproto.ir.Field
	5,  // 4: oghamproto.ir.Type.oneofs:type_name -> oghamproto.ir.OneofGroup
	3,  // 5: oghamproto.ir.Type.nested_types:type_name -> oghamproto.ir.Type
	7,  // 6: oghamproto.ir.Type.nested_enums:type_name -> oghamproto.ir.Enum
	17, // 7: oghamproto.ir.Type.annotations:type_name -> oghamproto.ir.AnnotationCall
	32, // 8: oghamproto.ir.Type.back_references:type_name -> oghamproto.ir.TypeBackRef
	27, // 9: oghamproto.ir.Type.trace:type_name -> oghamproto.ir.TypeTrace
	34, // 10: oghamproto.ir.Type.location:type_name -> oghamproto.common.SourceLocation
	1,  // 11: oghamproto.ir.Type.module:type_name -> oghamproto.ir.ModuleInfo
	12, // 12: oghamproto.ir.Field.type:type_name -> oghamproto.ir.TypeReference
	17, // 13: oghamproto.ir.Field.annotations:type_name -> oghamproto.ir.AnnotationCall
	25, // 14: oghamproto.ir.Field.mapping:type_name -> oghamproto.ir.FieldMapping
	30, // 15: oghamproto.ir.Field.trace:type_name -> oghamproto.ir.FieldTrace
	34, // 16: oghamproto.ir.Field.location:type_name -> oghamproto.common.SourceLocation
	6,  // 17: oghamproto.ir.OneofGroup.fields:type_name -> oghamproto.ir.OneofField
	17, // 18: oghamproto.ir.OneofGroup.annotations:type_name -> oghamproto.ir.AnnotationCall
	34, // 19: oghamproto.ir.OneofGroup.location:type_name -> oghamproto.common.SourceLocation
	12, // 20: oghamproto.ir.OneofField.type:type_name -> oghamproto.ir.TypeReference
	17, // 21: oghamproto.ir.OneofField.annotations:type_name -> oghamproto.ir.AnnotationCall
	25, // 22: oghamproto.ir.OneofField.mapping:type_name -> oghamproto.ir.FieldMapping
	34, // 23: oghamproto.ir.OneofField.location:type_name -> oghamproto.common.SourceLocation
	8,  // 24: oghamproto.ir.Enum.values:type_name -> oghamproto.ir.EnumValue
	17, // 25: oghamproto.ir.Enum.annotations:type_name -> oghamproto.ir.AnnotationCall
	34, // 26: oghamproto.ir.Enum.location:type_name -> oghamproto.common.SourceLocation
	1,  // 27: oghamproto.ir.Enum.module:type_name -> oghamproto.ir.ModuleInfo
	17, // 28: oghamproto.ir.EnumValue.annotations:type_name -> oghamproto.ir.AnnotationCall
	34, // 29: oghamproto.ir.EnumValue.location:type_name -> oghamproto.common.SourceLocation
	10, // 30: oghamproto.ir.Service.rpcs:type_name -> oghamproto.ir.Rpc
	17, // 31: oghamproto.ir.Service.annotations:type_name -> oghamproto.ir.AnnotationCall
	34, // 32: oghamproto.ir.Service.location:type_name -> oghamproto.common.SourceLocation
	1,  // 33: oghamproto.ir.Service.module:type_name -> oghamproto.ir.ModuleInfo
	11, // 34: oghamproto.ir.Rpc.input:type_name -> oghamproto.ir.RpcParam
	11, // 35: oghamproto.ir.Rpc.output:type_name -> oghamproto.ir.RpcParam
	17, // 36: oghamproto.ir.Rpc.annotations:type_name -> oghamproto.ir.AnnotationCall
	34, // 37: oghamproto.ir.Rpc.location:type_name -> oghamproto.common.SourceLocation
	12, // 38: oghamproto.ir.RpcParam.type:type_name -> oghamproto.ir.TypeReference
	13, // 39: oghamproto.ir.TypeReference.scalar:type_name -> oghamproto.ir.ScalarType
	14, // 40: oghamproto.ir.TypeReference.message_type:type_name -> oghamproto.ir.MessageType
	15, // 41: oghamproto.ir.TypeReference.enum_type:type_name -> oghamproto.ir.EnumType
	16, // 42: oghamproto.ir.TypeReference.map:type_name -> oghamproto.ir.MapType
	0,  // 43: oghamproto.ir.ScalarType.scalar_kind:type_name -> oghamproto.ir.ScalarKind
	4,  // 44: oghamproto.ir.MessageType.fields:type_name -> oghamproto.ir.Field
	5,  // 45: oghamproto.ir.MessageType.oneofs:type_name -> oghamproto.ir.OneofGroup
	7,  // 46: oghamproto.ir.MessageType.nested_enums:type_name -> oghamproto.ir.Enum
	17, // 47: oghamproto.ir.MessageType.annotations:type_name -> oghamproto.ir.AnnotationCall
	8,  // 48: oghamproto.ir.EnumType.values:type_name -> oghamproto.ir.EnumValue
	12, // 49: oghamproto.ir.MapType.key:type_name -> oghamproto.ir.TypeReference
	12, // 50: oghamproto.ir.MapType.value:type_name -> oghamproto.ir.TypeReference
	18, // 51: oghamproto.ir.AnnotationCall.arguments:type_name -> oghamproto.ir.AnnotationArgument
	22, // 52: oghamproto.ir.AnnotationCall.definition:type_name -> oghamproto.ir.AnnotationDefinition
	34, // 53: oghamproto.ir.AnnotationCall.location:type_name -> oghamproto.common.SourceLocation
	19, // 54: oghamproto.ir.AnnotationArgument.value:type_name -> oghamproto.ir.AnnotationLiteral
	20, // 55: oghamproto.ir.AnnotationLiteral.struct_value:type_name -> oghamproto.ir.AnnotationStruct
	21, // 56: oghamproto.ir.AnnotationLiteral.list_value:type_name -> oghamproto.ir.AnnotationList
	33, // 57: oghamproto.ir.AnnotationStruct.fields:type_name -> oghamproto.ir.AnnotationStruct.FieldsEntry
	19, // 58: oghamproto.ir.AnnotationList.values:type_name -> oghamproto.ir.AnnotationLiteral
	23, // 59: oghamproto.ir.AnnotationDefinition.parameters:type_name -> oghamproto.ir.AnnotationParameter
	24, // 60: oghamproto.ir.AnnotationDefinition.compositions:type_name -> oghamproto.ir.AnnotationCompositionRef
	12, // 61: oghamproto.ir.AnnotationParameter.type:type_name -> oghamproto.ir.TypeReference
	19, // 62: oghamproto.ir.AnnotationParameter.default_value:type_name -> oghamproto.ir.AnnotationLiteral
	18, // 63: oghamproto.ir.AnnotationCompositionRef.arguments:type_name -> oghamproto.ir.AnnotationArgument
	26, // 64: oghamproto.ir.FieldMapping.chain:type_name -> oghamproto.ir.MappingLink
	12, // 65: oghamproto.ir.MappingLink.source_field_type:type_name -> oghamproto.ir.TypeReference
	17, // 66: oghamproto.ir.MappingLink.source_field_annotations:type_name -> oghamproto.ir.AnnotationCall
	28, // 67: oghamproto.ir.TypeTrace.generic:type_name -> oghamproto.ir.GenericOrigin
	29, // 68: oghamproto.ir.TypeTrace.pick_omit:type_name -> oghamproto.ir.PickOmitOrigin
	31, // 69: oghamproto.ir.FieldTrace.shape:type_name -> oghamproto.ir.ShapeOrigin
	34, // 70: oghamproto.ir.ShapeOrigin.shape_location:type_name -> oghamproto.common.SourceLocation
	19, // 71: oghamproto.ir.AnnotationStruct.FieldsEntry.value:type_name -> oghamproto.ir.AnnotationLiteral
	72, // [72:72] is the sub-list for method output_type
	72, // [72:72] is the sub-list for method input_type
	72, // [72:72] is the sub-list for extension type_name
	72, // [72:72] is the sub-list for extension extendee
	0,  // [0:72] is the sub-list for field type_name
}

func init() { file_oghamproto_ir_types_proto_init() }
func file_oghamproto_ir_types_proto_init() {
	if File_oghamproto_ir_types_proto != nil {
		return
	}
	file_oghamproto_ir_types_proto_msgTypes[11].OneofWrappers = []any{
		(*TypeReference_Scalar)(nil),
		(*TypeReference_MessageType)(nil),
		(*TypeReference_EnumType)(nil),
		(*TypeReference_Map)(nil),
	}
	file_oghamproto_ir_types_proto_msgTypes[18].OneofWrappers = []any{
		(*AnnotationLiteral_StringValue)(nil),
		(*AnnotationLiteral_IntValue)(nil),
		(*AnnotationLiteral_FloatValue)(nil),
		(*AnnotationLiteral_BoolValue)(nil),
		(*AnnotationLiteral_StructValue)(nil),
		(*AnnotationLiteral_ListValue)(nil),
	}
	file_oghamproto_ir_types_proto_msgTypes[26].OneofWrappers = []any{
		(*TypeTrace_Generic)(nil),
		(*TypeTrace_PickOmit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oghamproto_ir_types_proto_rawDesc), len(file_oghamproto_ir_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oghamproto_ir_types_proto_goTypes,
		DependencyIndexes: file_oghamproto_ir_types_proto_depIdxs,
		EnumInfos:         file_oghamproto_ir_types_proto_enumTypes,
		MessageInfos:      file_oghamproto_ir_types_proto_msgTypes,
	}.Build()
	File_oghamproto_ir_types_proto = out.File
	file_oghamproto_ir_types_proto_goTypes = nil
	file_oghamproto_ir_types_proto_depIdxs = nil
}
