// ogham-gen-go generates Go structs, enums, getters, and converters from Ogham IR.
//
// Output layout: one directory per ogham package with proper Go imports.
//
//	gen/go/
//	├── store/store.go        ← own package types
//	├── common/common.go      ← dependency package
//	└── user/user.go          ← dependency package
//
// Options (from ogham.gen.yaml opts):
//
//	go_package_prefix — override import prefix (default: module_path/out)
//	protowire         — "true" to generate protobuf wire marshal/unmarshal
//	json_jx           — "true" to generate go-faster/jx Marshal/Unmarshal methods
//	arrow             — reserved for future Apache Arrow support
package main

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/oghamlang/go/oghamgen"
	"github.com/oghamlang/go/oghamproto/compiler"
	"github.com/oghamlang/go/oghamproto/ir"
)

// pkgBundle groups types/enums/services belonging to a single ogham package.
type pkgBundle struct {
	oghamPkg string // "store", "common", etc.
	types    []*ir.Type
	enums    []*ir.Enum
	services []*ir.Service
}

func main() {
	oghamgen.Run(func(req *compiler.OghamCompileRequest) (*compiler.OghamCompileResponse, error) {
		module := req.Module
		if module == nil {
			return &compiler.OghamCompileResponse{}, nil
		}

		opts := req.Options

		// Compute Go import prefix: module_path/out or explicit override.
		importPrefix := computeImportPrefix(req.ModulePath, req.OutputDir, opts)

		// Group declarations by source package.
		bundles := groupByPackage(module)

		resp := &compiler.OghamCompileResponse{}

		// Generate one directory per package.
		for _, b := range bundles {
			files := genPackage(b, importPrefix, bundles)
			resp.Files = append(resp.Files, files...)
		}

		return resp, nil
	})
}

// computeImportPrefix returns the Go import path prefix for generated packages.
// Default: module_path + "/" + output_dir (cleaned). Override via go_package_prefix opt.
func computeImportPrefix(modulePath, outputDir string, opts map[string]string) string {
	if v, ok := opts["go_package_prefix"]; ok && v != "" {
		return strings.TrimRight(v, "/")
	}
	if modulePath == "" {
		return ""
	}
	out := strings.TrimRight(outputDir, "/")
	out = strings.TrimPrefix(out, "./")
	if out == "" || out == "." {
		return modulePath
	}
	return modulePath + "/" + out
}

// groupByPackage collects types/enums/services into bundles keyed by ogham package.
func groupByPackage(module *ir.Module) map[string]*pkgBundle {
	bundles := map[string]*pkgBundle{}

	ensure := func(pkg string) *pkgBundle {
		if b, ok := bundles[pkg]; ok {
			return b
		}
		b := &pkgBundle{oghamPkg: pkg}
		bundles[pkg] = b
		return b
	}

	for _, ty := range module.Types {
		pkg := sourcePackage(ty.Module, module.Package)
		ensure(pkg).types = append(ensure(pkg).types, ty)
	}
	for _, en := range module.Enums {
		pkg := sourcePackage(en.Module, module.Package)
		ensure(pkg).enums = append(ensure(pkg).enums, en)
	}
	for _, svc := range module.Services {
		pkg := sourcePackage(svc.Module, module.Package)
		ensure(pkg).services = append(ensure(pkg).services, svc)
	}

	return bundles
}

// sourcePackage returns the ogham package name from ModuleInfo, falling back to the module's own package.
func sourcePackage(mi *ir.ModuleInfo, fallback string) string {
	if mi != nil && mi.Package != "" {
		return mi.Package
	}
	return fallback
}

// genPackage generates Go files for one ogham package bundle.
func genPackage(b *pkgBundle, importPrefix string, allBundles map[string]*pkgBundle) []*compiler.GeneratedFile {
	goPkg := goPackageName(b.oghamPkg)

	// Collect cross-package imports needed by this bundle.
	imports := collectImports(b, importPrefix, allBundles)

	w := oghamgen.NewCodeWriter()
	w.Comment("Code generated by ogham-gen-go. DO NOT EDIT.")
	w.Line("package %s", goPkg)
	w.Newline()

	// Imports block
	if len(imports) > 0 {
		needsFmt := bundleNeedsFmt(b)
		w.Line("import (")
		w.Indent()
		if needsFmt {
			w.Line("%q", "fmt")
		}
		// Sort for deterministic output
		sortedImports := sortedKeys(imports)
		for _, alias := range sortedImports {
			importPath := imports[alias]
			if alias != filepath.Base(importPath) {
				w.Line("%s %q", alias, importPath)
			} else {
				w.Line("%q", importPath)
			}
		}
		w.Dedent()
		w.Line(")")
		w.Newline()
	} else if bundleNeedsFmt(b) {
		w.Line("import %q", "fmt")
		w.Newline()
	}

	// Enums
	for _, en := range b.enums {
		genEnum(w, en)
		w.Newline()
	}

	// Types
	for _, ty := range b.types {
		genType(w, ty, b.oghamPkg, importPrefix, allBundles)
		w.Newline()
		genGetters(w, ty, b.oghamPkg, importPrefix, allBundles)
		w.Newline()
	}

	// Converters
	for _, ty := range b.types {
		genConverters(w, ty, b.oghamPkg)
	}

	filename := filepath.Join(goPkg, goPkg+".go")
	return []*compiler.GeneratedFile{w.ToFile(filename)}
}

// collectImports returns alias→importPath for cross-package type references.
func collectImports(b *pkgBundle, importPrefix string, allBundles map[string]*pkgBundle) map[string]string {
	needed := map[string]bool{}

	// Scan all type references in this bundle for cross-package refs.
	for _, ty := range b.types {
		for _, f := range ty.Fields {
			collectTypeRefPackages(f.Type, b.oghamPkg, needed)
		}
		for _, o := range ty.Oneofs {
			for _, f := range o.Fields {
				collectTypeRefPackages(f.Type, b.oghamPkg, needed)
			}
		}
	}
	for _, svc := range b.services {
		for _, rpc := range svc.Rpcs {
			if rpc.Input != nil {
				collectTypeRefPackages(rpc.Input.Type, b.oghamPkg, needed)
			}
			if rpc.Output != nil {
				collectTypeRefPackages(rpc.Output.Type, b.oghamPkg, needed)
			}
		}
	}

	imports := map[string]string{}
	for pkg := range needed {
		if _, exists := allBundles[pkg]; !exists {
			continue // unknown package, skip
		}
		goPkg := goPackageName(pkg)
		if importPrefix != "" {
			imports[goPkg] = importPrefix + "/" + goPkg
		}
	}
	return imports
}

// collectTypeRefPackages walks a TypeReference and adds any foreign package names to needed.
func collectTypeRefPackages(ref *ir.TypeReference, currentPkg string, needed map[string]bool) {
	if ref == nil {
		return
	}
	switch k := ref.Kind.(type) {
	case *ir.TypeReference_MessageType:
		pkg := packageFromFullName(k.MessageType.FullName)
		if pkg != "" && pkg != currentPkg {
			needed[pkg] = true
		}
		// Recurse into message fields
		for _, f := range k.MessageType.Fields {
			collectTypeRefPackages(f.Type, currentPkg, needed)
		}
	case *ir.TypeReference_EnumType:
		pkg := packageFromFullName(k.EnumType.FullName)
		if pkg != "" && pkg != currentPkg {
			needed[pkg] = true
		}
	case *ir.TypeReference_Map:
		collectTypeRefPackages(k.Map.Key, currentPkg, needed)
		collectTypeRefPackages(k.Map.Value, currentPkg, needed)
	}
}

// packageFromFullName extracts package from "store.User" → "store".
func packageFromFullName(fullName string) string {
	if i := strings.LastIndex(fullName, "."); i >= 0 {
		return fullName[:i]
	}
	return ""
}

// ── Enum generation ────────────────────────────────────────────────────

func genEnum(w *oghamgen.CodeWriter, en *ir.Enum) {
	typeName := oghamgen.ToPascalCase(en.Name)

	w.Comment("%s enum.", typeName)
	w.Line("type %s int32", typeName)
	w.Newline()

	w.Line("const (")
	w.Indent()
	for _, v := range en.Values {
		constName := fmt.Sprintf("%s_%s", typeName, oghamgen.ToScreamingSnakeCase(v.Name))
		w.Line("%s %s = %d", constName, typeName, v.Number)
	}
	w.Dedent()
	w.Line(")")
	w.Newline()

	// String method
	w.Open("func (x %s) String() string {", typeName)
	w.Open("switch x {")
	for _, v := range en.Values {
		constName := fmt.Sprintf("%s_%s", typeName, oghamgen.ToScreamingSnakeCase(v.Name))
		w.Line("case %s:", constName)
		w.Indent()
		w.Line("return %q", v.Name)
		w.Dedent()
	}
	w.Line("default:")
	w.Indent()
	w.Line("return fmt.Sprintf(\"%s(%%d)\", x)", typeName)
	w.Dedent()
	w.Close("}")
	w.Close("}")
}

// ── Type/struct generation ─────────────────────────────────────────────

func genType(w *oghamgen.CodeWriter, ty *ir.Type, currentPkg, importPrefix string, allBundles map[string]*pkgBundle) {
	structName := oghamgen.ToPascalCase(ty.Name)

	w.Comment("%s message.", structName)
	w.Open("type %s struct {", structName)

	for _, f := range ty.Fields {
		goType := irTypeToGo(f.Type, f.IsOptional, f.IsRepeated, currentPkg)
		fieldName := oghamgen.ToPascalCase(f.Name)
		jsonTag := jsonTagFor(f)
		w.Line("%s %s `json:%q`", fieldName, goType, jsonTag)
	}

	// Oneofs
	for _, oneof := range ty.Oneofs {
		ifaceName := fmt.Sprintf("is%s_%s", structName, oghamgen.ToPascalCase(oneof.Name))
		fieldName := oghamgen.ToPascalCase(oneof.Name)
		w.Line("%s %s `json:\"-\"`", fieldName, ifaceName)
	}

	w.Close("}")

	// Oneof interfaces + variant types
	for _, oneof := range ty.Oneofs {
		genOneof(w, structName, oneof, currentPkg)
	}
}

func genOneof(w *oghamgen.CodeWriter, parentName string, oneof *ir.OneofGroup, currentPkg string) {
	ifaceName := fmt.Sprintf("is%s_%s", parentName, oghamgen.ToPascalCase(oneof.Name))

	w.Newline()
	w.Open("type %s interface {", ifaceName)
	w.Line("%s()", ifaceName)
	w.Close("}")

	for _, f := range oneof.Fields {
		variantName := fmt.Sprintf("%s_%s", parentName, oghamgen.ToPascalCase(f.Name))
		goType := irTypeToGo(f.Type, false, false, currentPkg)
		w.Newline()
		w.Open("type %s struct {", variantName)
		w.Line("%s %s", oghamgen.ToPascalCase(f.Name), goType)
		w.Close("}")
		w.Newline()
		w.Line("func (*%s) %s() {}", variantName, ifaceName)
	}
}

// ── Getters ────────────────────────────────────────────────────────────

func genGetters(w *oghamgen.CodeWriter, ty *ir.Type, currentPkg, importPrefix string, allBundles map[string]*pkgBundle) {
	structName := oghamgen.ToPascalCase(ty.Name)

	for _, f := range ty.Fields {
		goType := irTypeToGo(f.Type, f.IsOptional, f.IsRepeated, currentPkg)
		fieldName := oghamgen.ToPascalCase(f.Name)
		getterName := fmt.Sprintf("Get%s", fieldName)

		w.Open("func (x *%s) %s() %s {", structName, getterName, goType)
		w.Open("if x != nil {")
		w.Line("return x.%s", fieldName)
		w.Close("}")
		w.Line("return %s", zeroValue(goType))
		w.Close("}")
		w.Newline()
	}
}

// ── Converters (projections) ───────────────────────────────────────────

func genConverters(w *oghamgen.CodeWriter, ty *ir.Type, currentPkg string) {
	// Check if any field has a mapping
	hasMappings := false
	for _, f := range ty.Fields {
		if f.Mapping != nil && len(f.Mapping.Chain) > 0 {
			hasMappings = true
			break
		}
	}
	if !hasMappings {
		return
	}

	structName := oghamgen.ToPascalCase(ty.Name)

	// Group mappings by source type
	sources := map[string]bool{}
	for _, f := range ty.Fields {
		if f.Mapping != nil && len(f.Mapping.Chain) > 0 {
			link := f.Mapping.Chain[0]
			if len(link.Path) > 0 {
				sources[link.Path[0]] = true
			}
		}
	}

	for srcName := range sources {
		srcStructName := oghamgen.ToPascalCase(srcName)
		funcName := fmt.Sprintf("%sFrom%s", structName, srcStructName)

		w.Comment("%s converts %s to %s.", funcName, srcStructName, structName)
		w.Open("func %s(src *%s) *%s {", funcName, srcStructName, structName)
		w.Open("if src == nil {")
		w.Line("return nil")
		w.Close("}")
		w.Open("return &%s{", structName)

		for _, f := range ty.Fields {
			if f.Mapping == nil || len(f.Mapping.Chain) == 0 {
				continue
			}
			link := f.Mapping.Chain[0]
			if len(link.Path) == 0 || link.Path[0] != srcName {
				continue
			}

			fieldName := oghamgen.ToPascalCase(f.Name)
			// Build accessor chain: src.FieldA.FieldB
			accessor := "src"
			for i := 1; i < len(link.Path); i++ {
				accessor += "." + oghamgen.ToPascalCase(link.Path[i])
			}

			w.Line("%s: %s,", fieldName, accessor)
		}

		w.Close("}")
		w.Close("}")
		w.Newline()
	}
}

// ── Type mapping ───────────────────────────────────────────────────────

// irTypeToGo converts an IR TypeReference to a Go type string.
// currentPkg is the ogham package being generated — types from other packages get qualified names.
func irTypeToGo(ref *ir.TypeReference, optional, repeated bool, currentPkg string) string {
	if ref == nil {
		return "[]byte"
	}

	var base string
	switch k := ref.Kind.(type) {
	case *ir.TypeReference_Scalar:
		base = scalarToGo(ir.ScalarKind(k.Scalar.ScalarKind))
	case *ir.TypeReference_MessageType:
		typeName := oghamgen.ToPascalCase(k.MessageType.Name)
		pkg := packageFromFullName(k.MessageType.FullName)
		if pkg != "" && pkg != currentPkg {
			// Cross-package reference: common.Money → common.Money
			base = "*" + goPackageName(pkg) + "." + typeName
		} else {
			base = "*" + typeName
		}
	case *ir.TypeReference_EnumType:
		typeName := oghamgen.ToPascalCase(k.EnumType.Name)
		pkg := packageFromFullName(k.EnumType.FullName)
		if pkg != "" && pkg != currentPkg {
			base = goPackageName(pkg) + "." + typeName
		} else {
			base = typeName
		}
	case *ir.TypeReference_Map:
		keyType := irTypeToGo(k.Map.Key, false, false, currentPkg)
		valType := irTypeToGo(k.Map.Value, false, false, currentPkg)
		return fmt.Sprintf("map[%s]%s", keyType, valType)
	default:
		base = "any"
	}

	if repeated {
		return "[]" + base
	}
	if optional && !strings.HasPrefix(base, "*") {
		return "*" + base
	}
	return base
}

func scalarToGo(kind ir.ScalarKind) string {
	switch kind {
	case ir.ScalarKind_BOOL:
		return "bool"
	case ir.ScalarKind_STRING:
		return "string"
	case ir.ScalarKind_BYTES:
		return "[]byte"
	case ir.ScalarKind_INT8:
		return "int8"
	case ir.ScalarKind_INT16:
		return "int16"
	case ir.ScalarKind_INT32:
		return "int32"
	case ir.ScalarKind_INT64:
		return "int64"
	case ir.ScalarKind_UINT8:
		return "uint8"
	case ir.ScalarKind_UINT16:
		return "uint16"
	case ir.ScalarKind_UINT32:
		return "uint32"
	case ir.ScalarKind_UINT64:
		return "uint64"
	case ir.ScalarKind_FLOAT:
		return "float32"
	case ir.ScalarKind_DOUBLE:
		return "float64"
	default:
		return "any"
	}
}

// ── Helpers ────────────────────────────────────────────────────────────

func jsonTagFor(f *ir.Field) string {
	tag := oghamgen.ToSnakeCase(f.Name)
	if f.IsOptional {
		tag += ",omitempty"
	}
	return tag
}

func zeroValue(goType string) string {
	if strings.HasPrefix(goType, "*") || strings.HasPrefix(goType, "[]") || strings.HasPrefix(goType, "map[") {
		return "nil"
	}
	switch goType {
	case "string":
		return `""`
	case "bool":
		return "false"
	case "int8", "int16", "int32", "int64", "uint8", "uint16", "uint32", "uint64", "float32", "float64":
		return "0"
	default:
		// Might be a cross-package enum type like common.Status
		return "0"
	}
}

func goPackageName(oghamPkg string) string {
	// "store" → "store", "example.models" → "models"
	parts := strings.Split(oghamPkg, ".")
	name := parts[len(parts)-1]
	name = strings.ReplaceAll(name, "-", "_")
	return strings.ToLower(name)
}

func optOr(opts map[string]string, key, def string) string {
	if v, ok := opts[key]; ok && v != "" {
		return v
	}
	return def
}

func bundleNeedsFmt(b *pkgBundle) bool {
	return len(b.enums) > 0
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
