// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: oghamproto/common/source.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Byte range in source text.
type SourceSpan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint32                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint32                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceSpan) Reset() {
	*x = SourceSpan{}
	mi := &file_oghamproto_common_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceSpan) ProtoMessage() {}

func (x *SourceSpan) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_common_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceSpan.ProtoReflect.Descriptor instead.
func (*SourceSpan) Descriptor() ([]byte, []int) {
	return file_oghamproto_common_source_proto_rawDescGZIP(), []int{0}
}

func (x *SourceSpan) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *SourceSpan) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

// Location in a source file.
type SourceLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Span          *SourceSpan            `protobuf:"bytes,2,opt,name=span,proto3" json:"span,omitempty"`
	Line          uint32                 `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Column        uint32                 `protobuf:"varint,4,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceLocation) Reset() {
	*x = SourceLocation{}
	mi := &file_oghamproto_common_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceLocation) ProtoMessage() {}

func (x *SourceLocation) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_common_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceLocation.ProtoReflect.Descriptor instead.
func (*SourceLocation) Descriptor() ([]byte, []int) {
	return file_oghamproto_common_source_proto_rawDescGZIP(), []int{1}
}

func (x *SourceLocation) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *SourceLocation) GetSpan() *SourceSpan {
	if x != nil {
		return x.Span
	}
	return nil
}

func (x *SourceLocation) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *SourceLocation) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

var File_oghamproto_common_source_proto protoreflect.FileDescriptor

const file_oghamproto_common_source_proto_rawDesc = "" +
	"\n" +
	"\x1eoghamproto/common/source.proto\x12\x11oghamproto.common\"4\n" +
	"\n" +
	"SourceSpan\x12\x14\n" +
	"\x05start\x18\x01 \x01(\rR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\rR\x03end\"\x83\x01\n" +
	"\x0eSourceLocation\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x121\n" +
	"\x04span\x18\x02 \x01(\v2\x1d.oghamproto.common.SourceSpanR\x04span\x12\x12\n" +
	"\x04line\x18\x03 \x01(\rR\x04line\x12\x16\n" +
	"\x06column\x18\x04 \x01(\rR\x06columnB+Z)github.com/oghamlang/go/oghamproto/commonb\x06proto3"

var (
	file_oghamproto_common_source_proto_rawDescOnce sync.Once
	file_oghamproto_common_source_proto_rawDescData []byte
)

func file_oghamproto_common_source_proto_rawDescGZIP() []byte {
	file_oghamproto_common_source_proto_rawDescOnce.Do(func() {
		file_oghamproto_common_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oghamproto_common_source_proto_rawDesc), len(file_oghamproto_common_source_proto_rawDesc)))
	})
	return file_oghamproto_common_source_proto_rawDescData
}

var file_oghamproto_common_source_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_oghamproto_common_source_proto_goTypes = []any{
	(*SourceSpan)(nil),     // 0: oghamproto.common.SourceSpan
	(*SourceLocation)(nil), // 1: oghamproto.common.SourceLocation
}
var file_oghamproto_common_source_proto_depIdxs = []int32{
	0, // 0: oghamproto.common.SourceLocation.span:type_name -> oghamproto.common.SourceSpan
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_oghamproto_common_source_proto_init() }
func file_oghamproto_common_source_proto_init() {
	if File_oghamproto_common_source_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oghamproto_common_source_proto_rawDesc), len(file_oghamproto_common_source_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oghamproto_common_source_proto_goTypes,
		DependencyIndexes: file_oghamproto_common_source_proto_depIdxs,
		MessageInfos:      file_oghamproto_common_source_proto_msgTypes,
	}.Build()
	File_oghamproto_common_source_proto = out.File
	file_oghamproto_common_source_proto_goTypes = nil
	file_oghamproto_common_source_proto_depIdxs = nil
}
