// @generated by protoc-gen-es v2.11.0 with parameter "import_extension=ts,json_types=true,valid_types=legacy_required+protovalidate_required,target=ts"
// @generated from file oghamproto/compiler/request.proto (package oghamproto.compiler, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Module, ModuleJson } from "../ir/types_pb.ts";
import { file_oghamproto_ir_types } from "../ir/types_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file oghamproto/compiler/request.proto.
 */
export const file_oghamproto_compiler_request: GenFile = /*@__PURE__*/
  fileDesc("CiFvZ2hhbXByb3RvL2NvbXBpbGVyL3JlcXVlc3QucHJvdG8SE29naGFtcHJvdG8uY29tcGlsZXIi4gEKE09naGFtQ29tcGlsZVJlcXVlc3QSGAoQY29tcGlsZXJfdmVyc2lvbhgBIAEoCRIlCgZtb2R1bGUYAiABKAsyFS5vZ2hhbXByb3RvLmlyLk1vZHVsZRJGCgdvcHRpb25zGAMgAygLMjUub2doYW1wcm90by5jb21waWxlci5PZ2hhbUNvbXBpbGVSZXF1ZXN0Lk9wdGlvbnNFbnRyeRISCgpvdXRwdXRfZGlyGAQgASgJGi4KDE9wdGlvbnNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBInwKFE9naGFtQ29tcGlsZVJlc3BvbnNlEjEKBWZpbGVzGAEgAygLMiIub2doYW1wcm90by5jb21waWxlci5HZW5lcmF0ZWRGaWxlEjEKBmVycm9ycxgCIAMoCzIhLm9naGFtcHJvdG8uY29tcGlsZXIuQ29tcGlsZUVycm9yIj4KDUdlbmVyYXRlZEZpbGUSDAoEbmFtZRgBIAEoCRIPCgdjb250ZW50GAIgASgMEg4KBmFwcGVuZBgDIAEoCCJ7CgxDb21waWxlRXJyb3ISDwoHbWVzc2FnZRgBIAEoCRIvCghzZXZlcml0eRgCIAEoDjIdLm9naGFtcHJvdG8uY29tcGlsZXIuU2V2ZXJpdHkSEwoLc291cmNlX3R5cGUYAyABKAkSFAoMc291cmNlX2ZpZWxkGAQgASgJKj8KCFNldmVyaXR5EhEKDVNFVkVSSVRZX05PTkUQABIJCgVFUlJPUhABEgsKB1dBUk5JTkcQAhIICgRJTkZPEAMycgoOT2doYW1QbHVnaW5BUEkSYAoHQ29tcGlsZRIoLm9naGFtcHJvdG8uY29tcGlsZXIuT2doYW1Db21waWxlUmVxdWVzdBopLm9naGFtcHJvdG8uY29tcGlsZXIuT2doYW1Db21waWxlUmVzcG9uc2UiAEItWitnaXRodWIuY29tL29naGFtbGFuZy9nby9vZ2hhbXByb3RvL2NvbXBpbGVyYgZwcm90bzM", [file_oghamproto_ir_types]);

/**
 * Sent to a plugin via stdin. Contains the fully resolved IR.
 *
 * @generated from message oghamproto.compiler.OghamCompileRequest
 */
export type OghamCompileRequest = Message<"oghamproto.compiler.OghamCompileRequest"> & {
  /**
   * Compiler version that produced this request.
   *
   * @generated from field: string compiler_version = 1;
   */
  compilerVersion: string;

  /**
   * The module being compiled.
   *
   * @generated from field: oghamproto.ir.Module module = 2;
   */
  module?: Module;

  /**
   * Plugin options from ogham.gen.yaml `opts` section.
   *
   * @generated from field: map<string, string> options = 3;
   */
  options: { [key: string]: string };

  /**
   * Output directory specified in ogham.gen.yaml.
   *
   * @generated from field: string output_dir = 4;
   */
  outputDir: string;
};

/**
 * Sent to a plugin via stdin. Contains the fully resolved IR.
 *
 * @generated from message oghamproto.compiler.OghamCompileRequest
 */
export type OghamCompileRequestJson = {
  /**
   * Compiler version that produced this request.
   *
   * @generated from field: string compiler_version = 1;
   */
  compilerVersion?: string;

  /**
   * The module being compiled.
   *
   * @generated from field: oghamproto.ir.Module module = 2;
   */
  module?: ModuleJson;

  /**
   * Plugin options from ogham.gen.yaml `opts` section.
   *
   * @generated from field: map<string, string> options = 3;
   */
  options?: { [key: string]: string };

  /**
   * Output directory specified in ogham.gen.yaml.
   *
   * @generated from field: string output_dir = 4;
   */
  outputDir?: string;
};

export type OghamCompileRequestValid = OghamCompileRequest;

/**
 * Describes the message oghamproto.compiler.OghamCompileRequest.
 * Use `create(OghamCompileRequestSchema)` to create a new message.
 */
export const OghamCompileRequestSchema: GenMessage<OghamCompileRequest, {jsonType: OghamCompileRequestJson, validType: OghamCompileRequestValid}> = /*@__PURE__*/
  messageDesc(file_oghamproto_compiler_request, 0);

/**
 * Returned by a plugin via stdout.
 *
 * @generated from message oghamproto.compiler.OghamCompileResponse
 */
export type OghamCompileResponse = Message<"oghamproto.compiler.OghamCompileResponse"> & {
  /**
   * @generated from field: repeated oghamproto.compiler.GeneratedFile files = 1;
   */
  files: GeneratedFile[];

  /**
   * @generated from field: repeated oghamproto.compiler.CompileError errors = 2;
   */
  errors: CompileError[];
};

/**
 * Returned by a plugin via stdout.
 *
 * @generated from message oghamproto.compiler.OghamCompileResponse
 */
export type OghamCompileResponseJson = {
  /**
   * @generated from field: repeated oghamproto.compiler.GeneratedFile files = 1;
   */
  files?: GeneratedFileJson[];

  /**
   * @generated from field: repeated oghamproto.compiler.CompileError errors = 2;
   */
  errors?: CompileErrorJson[];
};

export type OghamCompileResponseValid = OghamCompileResponse;

/**
 * Describes the message oghamproto.compiler.OghamCompileResponse.
 * Use `create(OghamCompileResponseSchema)` to create a new message.
 */
export const OghamCompileResponseSchema: GenMessage<OghamCompileResponse, {jsonType: OghamCompileResponseJson, validType: OghamCompileResponseValid}> = /*@__PURE__*/
  messageDesc(file_oghamproto_compiler_request, 1);

/**
 * A file produced by a plugin.
 *
 * @generated from message oghamproto.compiler.GeneratedFile
 */
export type GeneratedFile = Message<"oghamproto.compiler.GeneratedFile"> & {
  /**
   * Path relative to output_dir.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * File contents.
   *
   * @generated from field: bytes content = 2;
   */
  content: Uint8Array;

  /**
   * If true, content is appended to existing file instead of overwriting.
   *
   * @generated from field: bool append = 3;
   */
  append: boolean;
};

/**
 * A file produced by a plugin.
 *
 * @generated from message oghamproto.compiler.GeneratedFile
 */
export type GeneratedFileJson = {
  /**
   * Path relative to output_dir.
   *
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * File contents.
   *
   * @generated from field: bytes content = 2;
   */
  content?: string;

  /**
   * If true, content is appended to existing file instead of overwriting.
   *
   * @generated from field: bool append = 3;
   */
  append?: boolean;
};

export type GeneratedFileValid = GeneratedFile;

/**
 * Describes the message oghamproto.compiler.GeneratedFile.
 * Use `create(GeneratedFileSchema)` to create a new message.
 */
export const GeneratedFileSchema: GenMessage<GeneratedFile, {jsonType: GeneratedFileJson, validType: GeneratedFileValid}> = /*@__PURE__*/
  messageDesc(file_oghamproto_compiler_request, 2);

/**
 * An error reported by a plugin.
 *
 * @generated from message oghamproto.compiler.CompileError
 */
export type CompileError = Message<"oghamproto.compiler.CompileError"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: oghamproto.compiler.Severity severity = 2;
   */
  severity: Severity;

  /**
   * Optional: source location that caused the error.
   *
   * @generated from field: string source_type = 3;
   */
  sourceType: string;

  /**
   * @generated from field: string source_field = 4;
   */
  sourceField: string;
};

/**
 * An error reported by a plugin.
 *
 * @generated from message oghamproto.compiler.CompileError
 */
export type CompileErrorJson = {
  /**
   * @generated from field: string message = 1;
   */
  message?: string;

  /**
   * @generated from field: oghamproto.compiler.Severity severity = 2;
   */
  severity?: SeverityJson;

  /**
   * Optional: source location that caused the error.
   *
   * @generated from field: string source_type = 3;
   */
  sourceType?: string;

  /**
   * @generated from field: string source_field = 4;
   */
  sourceField?: string;
};

export type CompileErrorValid = CompileError;

/**
 * Describes the message oghamproto.compiler.CompileError.
 * Use `create(CompileErrorSchema)` to create a new message.
 */
export const CompileErrorSchema: GenMessage<CompileError, {jsonType: CompileErrorJson, validType: CompileErrorValid}> = /*@__PURE__*/
  messageDesc(file_oghamproto_compiler_request, 3);

/**
 * @generated from enum oghamproto.compiler.Severity
 */
export enum Severity {
  /**
   * @generated from enum value: SEVERITY_NONE = 0;
   */
  SEVERITY_NONE = 0,

  /**
   * @generated from enum value: ERROR = 1;
   */
  ERROR = 1,

  /**
   * @generated from enum value: WARNING = 2;
   */
  WARNING = 2,

  /**
   * @generated from enum value: INFO = 3;
   */
  INFO = 3,
}

/**
 * @generated from enum oghamproto.compiler.Severity
 */
export type SeverityJson = "SEVERITY_NONE" | "ERROR" | "WARNING" | "INFO";

/**
 * Describes the enum oghamproto.compiler.Severity.
 */
export const SeveritySchema: GenEnum<Severity, SeverityJson> = /*@__PURE__*/
  enumDesc(file_oghamproto_compiler_request, 0);

/**
 * gRPC service for remote plugins (ogham serve --plugin <name> --address :50051).
 *
 * @generated from service oghamproto.compiler.OghamPluginAPI
 */
export const OghamPluginAPI: GenService<{
  /**
   * Unary: compile a module and return generated files.
   *
   * @generated from rpc oghamproto.compiler.OghamPluginAPI.Compile
   */
  compile: {
    methodKind: "unary";
    input: typeof OghamCompileRequestSchema;
    output: typeof OghamCompileResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_oghamproto_compiler_request, 0);

