//! ogham-gen-proto — export .proto files from Ogham schemas.
//!
//! Output layout: one .proto file per ogham package with proper imports.
//!
//!   proto/
//!   ├── store.proto        ← own package
//!   ├── common.proto       ← dependency
//!   └── user.proto         ← dependency
//!
//! Options (from ogham.gen.yaml opts):
//!
//!   go_package_prefix       — Go import prefix (default: module_path/out)
//!   java_package_prefix     — Java package prefix (e.g. "com.myteam")
//!   java_outer_classname    — explicit outer class (default: derived from filename)
//!   csharp_namespace_prefix — C# namespace prefix (e.g. "MyTeam.Proto")
//!   swift_prefix            — Swift class prefix
//!   php_namespace_prefix    — PHP namespace prefix
//!   ruby_package_prefix     — Ruby module prefix
//!   objc_class_prefix       — Objective-C class prefix
//!   import_prefix           — prefix for proto package and import paths
//!                             e.g. "proto" → package proto.store; import "proto/common.proto";
//!   optimize_for            — SPEED, CODE_SIZE, or LITE_RUNTIME

use std::collections::{BTreeMap, BTreeSet};
use oghamgen::*;

fn main() {
    run(|req: CompileRequest| {
        let module = req.module.as_ref().ok_or("no module in request")?;
        let opts = &req.options;
        let module_path = &req.module_path;
        let output_dir = &req.output_dir;

        // import_prefix: prepended to proto package, import paths, and filenames.
        // e.g. "proto" → package proto.store; import "proto/common.proto";
        let import_prefix = opts.get("import_prefix")
            .filter(|v| !v.is_empty())
            .map(|v| v.trim_matches('/').trim_matches('.').to_string())
            .unwrap_or_default();

        // Group declarations by source package.
        let bundles = group_by_package(module);

        let mut resp = CompileResponse::default();

        for (_, bundle) in &bundles {
            let file = gen_proto_file(bundle, module_path, output_dir, opts, &bundles, &import_prefix);
            resp.files.push(file);
        }

        Ok(resp)
    });
}

// ── Package bundling ──────────────────────────────────────────────────

struct PkgBundle<'a> {
    ogham_pkg: String,
    types: Vec<&'a Type>,
    enums: Vec<&'a Enum>,
    services: Vec<&'a Service>,
}

fn group_by_package<'a>(module: &'a Module) -> BTreeMap<String, PkgBundle<'a>> {
    let mut bundles: BTreeMap<String, PkgBundle<'a>> = BTreeMap::new();

    let ensure = |bundles: &mut BTreeMap<String, PkgBundle<'a>>, pkg: &str| {
        bundles.entry(pkg.to_string()).or_insert_with(|| PkgBundle {
            ogham_pkg: pkg.to_string(),
            types: Vec::new(),
            enums: Vec::new(),
            services: Vec::new(),
        });
    };

    for ty in &module.types {
        let pkg = source_package(ty.module.as_ref(), &module.package);
        ensure(&mut bundles, &pkg);
        bundles.get_mut(&pkg).unwrap().types.push(ty);
    }
    for en in &module.enums {
        let pkg = source_package(en.module.as_ref(), &module.package);
        ensure(&mut bundles, &pkg);
        bundles.get_mut(&pkg).unwrap().enums.push(en);
    }
    for svc in &module.services {
        let pkg = source_package(svc.module.as_ref(), &module.package);
        ensure(&mut bundles, &pkg);
        bundles.get_mut(&pkg).unwrap().services.push(svc);
    }

    bundles
}

fn source_package(mi: Option<&ModuleInfo>, fallback: &str) -> String {
    mi.and_then(|m| {
        if m.package.is_empty() {
            None
        } else {
            Some(m.package.clone())
        }
    })
    .unwrap_or_else(|| fallback.to_string())
}

// ── Proto file generation ─────────────────────────────────────────────

fn gen_proto_file(
    bundle: &PkgBundle,
    module_path: &str,
    output_dir: &str,
    opts: &std::collections::HashMap<String, String>,
    all_bundles: &BTreeMap<String, PkgBundle>,
    import_prefix: &str,
) -> GeneratedFile {
    let pkg = &bundle.ogham_pkg;
    let proto_pkg = prefixed_proto_package(import_prefix, pkg);
    let mut w = CodeWriter::with_indent("  ");

    // Header
    w.raw("// Generated by ogham-gen-proto. DO NOT EDIT.");
    w.raw("syntax = \"proto3\";");
    w.newline();
    w.raw(&format!("package {};", proto_pkg));
    w.newline();

    // File-level options
    emit_file_options(&mut w, pkg, module_path, output_dir, opts);

    // Cross-package imports
    let imported_pkgs = collect_imported_packages(bundle, pkg, all_bundles);
    for imp_pkg in &imported_pkgs {
        let import_path = prefixed_path(import_prefix, &format!("{}.proto", imp_pkg));
        w.raw(&format!("import \"{}\";", import_path));
    }

    // Well-known type imports
    let needs_empty = bundle.services.iter().any(|s| {
        s.rpcs.iter().any(|r| {
            r.input.as_ref().is_some_and(|p| p.is_void)
                || r.output.as_ref().is_some_and(|p| p.is_void)
        })
    });
    let has_annotations = bundle_has_annotations(bundle);
    let wkt_imports = collect_wkt_imports(bundle);

    if needs_empty {
        w.raw("import \"google/protobuf/empty.proto\";");
    }
    if has_annotations {
        w.raw("import \"google/protobuf/descriptor.proto\";");
    }
    for wkt_import in &wkt_imports {
        w.raw(&format!("import \"{}\";", wkt_import));
    }
    if !imported_pkgs.is_empty() || needs_empty || has_annotations || !wkt_imports.is_empty() {
        w.newline();
    }

    // OghamAnnotation extension (if annotations present)
    if has_annotations {
        emit_ogham_options(&mut w);
        w.newline();
    }

    // Enums (skip well-known proto types)
    for en in &bundle.enums {
        if well_known_proto_type(&en.full_name).is_some() {
            continue;
        }
        emit_enum(&mut w, en);
        w.newline();
    }

    // Messages (skip well-known proto types)
    for ty in &bundle.types {
        if well_known_proto_type(&ty.full_name).is_some() {
            continue;
        }
        emit_message(&mut w, ty, pkg);
        w.newline();
    }

    // Services
    for svc in &bundle.services {
        emit_service(&mut w, svc, pkg);
        w.newline();
    }

    let filename = format!("{}.proto", pkg);
    w.to_file(&filename)
}

// ── File-level options ────────────────────────────────────────────────

fn emit_file_options(
    w: &mut CodeWriter,
    pkg: &str,
    module_path: &str,
    output_dir: &str,
    opts: &std::collections::HashMap<String, String>,
) {
    let mut any_option = false;

    // go_package
    if let Some(val) = compute_go_package(opts, pkg, module_path, output_dir) {
        w.raw(&format!("option go_package = \"{}\";", val));
        any_option = true;
    }

    // java_package
    if let Some(val) = compute_dot_package(opts, "java_package_prefix", pkg) {
        w.raw(&format!("option java_package = \"{}\";", val));
        any_option = true;
    }

    // java_outer_classname
    if let Some(val) = opts.get("java_outer_classname") {
        if !val.is_empty() {
            w.raw(&format!("option java_outer_classname = \"{}\";", val));
            any_option = true;
        }
    }

    // csharp_namespace
    if let Some(val) = compute_namespace_option(opts, "csharp_namespace_prefix", pkg) {
        w.raw(&format!("option csharp_namespace = \"{}\";", val));
        any_option = true;
    }

    // swift_prefix
    if let Some(val) = opts.get("swift_prefix") {
        if !val.is_empty() {
            w.raw(&format!("option swift_prefix = \"{}\";", val));
            any_option = true;
        }
    }

    // php_namespace
    if let Some(val) = compute_namespace_option(opts, "php_namespace_prefix", pkg) {
        w.raw(&format!("option php_namespace = \"{}\";", val));
        any_option = true;
    }

    // ruby_package
    if let Some(val) = compute_namespace_option(opts, "ruby_package_prefix", pkg) {
        w.raw(&format!("option ruby_package = \"{}\";", val));
        any_option = true;
    }

    // objc_class_prefix
    if let Some(val) = opts.get("objc_class_prefix") {
        if !val.is_empty() {
            w.raw(&format!("option objc_class_prefix = \"{}\";", val));
            any_option = true;
        }
    }

    // optimize_for
    if let Some(val) = opts.get("optimize_for") {
        if !val.is_empty() {
            w.raw(&format!("option optimize_for = {};", val.to_uppercase()));
            any_option = true;
        }
    }

    if any_option {
        w.newline();
    }
}

/// Compute a path-style option (go_package).
/// If `<key>` is set in opts, use prefix + "/" + pkg.
/// For go_package, default to module_path/output_dir/pkg.
fn compute_go_package(
    opts: &std::collections::HashMap<String, String>,
    pkg: &str,
    module_path: &str,
    output_dir: &str,
) -> Option<String> {
    // Explicit prefix
    if let Some(prefix) = opts.get("go_package_prefix") {
        if !prefix.is_empty() {
            let prefix = prefix.trim_end_matches('/');
            return Some(format!("{}/{}", prefix, pkg));
        }
    }

    // Default: module_path/output_dir/pkg
    if !module_path.is_empty() {
        let out = output_dir
            .trim_end_matches('/')
            .trim_start_matches("./");
        let base = if out.is_empty() || out == "." {
            module_path.to_string()
        } else {
            format!("{}/{}", module_path, out)
        };
        return Some(format!("{}/{}", base, pkg));
    }

    None
}

/// Compute a dot-separated package option (java_package).
/// prefix + "." + pkg.
fn compute_dot_package(
    opts: &std::collections::HashMap<String, String>,
    prefix_key: &str,
    pkg: &str,
) -> Option<String> {
    opts.get(prefix_key).and_then(|prefix| {
        if prefix.is_empty() {
            None
        } else {
            Some(format!("{}.{}", prefix.trim_end_matches('.'), pkg))
        }
    })
}

/// Compute a namespace-style option (csharp, php, ruby).
/// prefix + "." + PascalCase(pkg).
fn compute_namespace_option(
    opts: &std::collections::HashMap<String, String>,
    prefix_key: &str,
    pkg: &str,
) -> Option<String> {
    opts.get(prefix_key).and_then(|prefix| {
        if prefix.is_empty() {
            None
        } else {
            Some(format!("{}.{}", prefix, to_pascal_case(pkg)))
        }
    })
}

// ── Cross-package imports ─────────────────────────────────────────────

fn collect_imported_packages(
    bundle: &PkgBundle,
    current_pkg: &str,
    all_bundles: &BTreeMap<String, PkgBundle>,
) -> BTreeSet<String> {
    let mut needed = BTreeSet::new();

    for ty in &bundle.types {
        for f in &ty.fields {
            collect_type_ref_packages(f.r#type.as_ref(), current_pkg, &mut needed);
        }
        for o in &ty.oneofs {
            for f in &o.fields {
                collect_type_ref_packages(f.r#type.as_ref(), current_pkg, &mut needed);
            }
        }
    }
    for svc in &bundle.services {
        for rpc in &svc.rpcs {
            if let Some(ref p) = rpc.input {
                collect_type_ref_packages(p.r#type.as_ref(), current_pkg, &mut needed);
            }
            if let Some(ref p) = rpc.output {
                collect_type_ref_packages(p.r#type.as_ref(), current_pkg, &mut needed);
            }
        }
    }

    // Only keep packages that actually exist in bundles
    needed.retain(|p| all_bundles.contains_key(p));
    needed
}

fn collect_type_ref_packages(
    tr: Option<&TypeReference>,
    current_pkg: &str,
    needed: &mut BTreeSet<String>,
) {
    let tr = match tr {
        Some(t) => t,
        None => return,
    };
    match &tr.kind {
        Some(type_reference::Kind::MessageType(m)) => {
            if let Some(pkg) = package_from_full_name(&m.full_name) {
                if pkg != current_pkg {
                    needed.insert(pkg.to_string());
                }
            }
            for f in &m.fields {
                collect_type_ref_packages(f.r#type.as_ref(), current_pkg, needed);
            }
        }
        Some(type_reference::Kind::EnumType(e)) => {
            if let Some(pkg) = package_from_full_name(&e.full_name) {
                if pkg != current_pkg {
                    needed.insert(pkg.to_string());
                }
            }
        }
        Some(type_reference::Kind::Map(m)) => {
            collect_type_ref_packages(m.key.as_deref(), current_pkg, needed);
            collect_type_ref_packages(m.value.as_deref(), current_pkg, needed);
        }
        _ => {}
    }
}

fn package_from_full_name(full_name: &str) -> Option<&str> {
    full_name.rfind('.').map(|i| &full_name[..i])
}

// ── Proto package name ────────────────────────────────────────────────

fn proto_package(ogham_package: &str) -> String {
    ogham_package.replace('/', ".")
}

/// Apply import_prefix to a proto package name.
/// "" + "store" → "store", "proto" + "store" → "proto.store"
fn prefixed_proto_package(import_prefix: &str, pkg: &str) -> String {
    if import_prefix.is_empty() {
        proto_package(pkg)
    } else {
        format!("{}.{}", import_prefix, proto_package(pkg))
    }
}

/// Apply import_prefix to a file path.
/// "" + "common.proto" → "common.proto", "proto" + "common.proto" → "proto/common.proto"
fn prefixed_path(import_prefix: &str, path: &str) -> String {
    if import_prefix.is_empty() {
        path.to_string()
    } else {
        format!("{}/{}", import_prefix, path)
    }
}

// ── Emit helpers ──────────────────────────────────────────────────────

fn emit_ogham_options(w: &mut CodeWriter) {
    w.raw("message OghamAnnotation {");
    w.raw("  string name = 1;");
    w.raw("  google.protobuf.Struct params = 2;");
    w.raw("}");
    w.newline();
    w.raw("extend google.protobuf.MessageOptions { repeated OghamAnnotation ogham_msg = 50000; }");
    w.raw("extend google.protobuf.FieldOptions { repeated OghamAnnotation ogham_field = 50001; }");
    w.raw("extend google.protobuf.OneofOptions { repeated OghamAnnotation ogham_oneof = 50002; }");
    w.raw("extend google.protobuf.EnumOptions { repeated OghamAnnotation ogham_enum = 50003; }");
    w.raw("extend google.protobuf.EnumValueOptions { repeated OghamAnnotation ogham_enum_value = 50004; }");
    w.raw("extend google.protobuf.ServiceOptions { repeated OghamAnnotation ogham_service = 50005; }");
    w.raw("extend google.protobuf.MethodOptions { repeated OghamAnnotation ogham_method = 50006; }");
}

fn emit_enum(w: &mut CodeWriter, en: &Enum) {
    emit_annotations_comment(w, &en.annotations);
    w.open(&format!("enum {} {{", en.name));
    for val in &en.values {
        let mut line = format!("{} = {};", val.name, val.number);
        if val.is_removed && !val.fallback.is_empty() {
            line = format!(
                "{} = {}; // @removed(fallback={})",
                val.name, val.number, val.fallback
            );
        }
        emit_annotations_comment(w, &val.annotations);
        w.line(&line);
    }
    w.close("}");
}

fn emit_message(w: &mut CodeWriter, ty: &Type, current_pkg: &str) {
    emit_annotations_comment(w, &ty.annotations);
    w.open(&format!("message {} {{", ty.name));

    // Fields
    for field in &ty.fields {
        emit_field(w, field, current_pkg);
    }

    // Oneofs
    for oneof in &ty.oneofs {
        emit_annotations_comment(w, &oneof.annotations);
        w.open(&format!("oneof {} {{", oneof.name));
        for field in &oneof.fields {
            let proto_type = type_ref_to_proto(field.r#type.as_ref(), current_pkg);
            emit_annotations_comment(w, &field.annotations);
            w.line(&format!("{} {} = {};", proto_type, field.name, field.number));
        }
        w.close("}");
    }

    // Nested enums
    for nested_enum in &ty.nested_enums {
        w.newline();
        emit_enum(w, nested_enum);
    }

    // Nested types
    for nested_type in &ty.nested_types {
        w.newline();
        emit_message(w, nested_type, current_pkg);
    }

    w.close("}");
}

fn emit_field(w: &mut CodeWriter, field: &Field, current_pkg: &str) {
    let proto_type = type_ref_to_proto(field.r#type.as_ref(), current_pkg);
    let mut prefix = String::new();

    if field.is_repeated {
        prefix = "repeated ".to_string();
    } else if field.is_optional {
        prefix = "optional ".to_string();
    }

    // Mapping comment
    let mapping_comment = if let Some(ref mapping) = field.mapping {
        if let Some(link) = mapping.chain.first() {
            let path: Vec<&str> = link.path.iter().map(|s| s.as_str()).collect();
            format!(" // <- {}", path.join("."))
        } else {
            String::new()
        }
    } else {
        String::new()
    };

    emit_annotations_comment(w, &field.annotations);
    w.line(&format!(
        "{}{} {} = {};{}",
        prefix, proto_type, field.name, field.number, mapping_comment
    ));
}

fn emit_service(w: &mut CodeWriter, svc: &Service, current_pkg: &str) {
    emit_annotations_comment(w, &svc.annotations);
    w.open(&format!("service {} {{", svc.name));

    for rpc in &svc.rpcs {
        let input = rpc_param_to_proto(rpc.input.as_ref(), current_pkg);
        let output = rpc_param_to_proto(rpc.output.as_ref(), current_pkg);
        emit_annotations_comment(w, &rpc.annotations);
        w.line(&format!("rpc {}({}) returns ({}) {{}}", rpc.name, input, output));
    }

    w.close("}");
}

fn emit_annotations_comment(w: &mut CodeWriter, annotations: &[AnnotationCall]) {
    for ann in annotations {
        let name = if ann.library.is_empty() {
            ann.name.clone()
        } else {
            format!("{}::{}", ann.library, ann.name)
        };
        if ann.arguments.is_empty() {
            w.comment("//", &format!("@{}", name));
        } else {
            let args: Vec<String> = ann
                .arguments
                .iter()
                .map(|a| {
                    let val = a
                        .value
                        .as_ref()
                        .map(literal_to_string)
                        .unwrap_or_default();
                    if a.name.is_empty() {
                        val
                    } else {
                        format!("{}={}", a.name, val)
                    }
                })
                .collect();
            w.comment("//", &format!("@{}({})", name, args.join(", ")));
        }
    }
}

// ── Type conversion ───────────────────────────────────────────────────

/// Convert a TypeReference to its proto3 type name.
/// Cross-package types use fully qualified proto names (e.g., "common.Money").
fn type_ref_to_proto(tr: Option<&TypeReference>, current_pkg: &str) -> String {
    let tr = match tr {
        Some(t) => t,
        None => return "bytes".to_string(),
    };

    match &tr.kind {
        Some(type_reference::Kind::Scalar(s)) => scalar_to_proto(s.scalar_kind),
        Some(type_reference::Kind::MessageType(m)) => {
            qualify_name(&m.name, &m.full_name, current_pkg)
        }
        Some(type_reference::Kind::EnumType(e)) => {
            qualify_name(&e.name, &e.full_name, current_pkg)
        }
        Some(type_reference::Kind::Map(m)) => {
            let key = type_ref_to_proto(m.key.as_deref(), current_pkg);
            let val = type_ref_to_proto(m.value.as_deref(), current_pkg);
            format!("map<{}, {}>", key, val)
        }
        None => "bytes".to_string(),
    }
}

/// If the type is from the current package, use short name.
/// If from another package, use fully qualified proto name.
/// Ogham std types are mapped to well-known proto types.
fn qualify_name(name: &str, full_name: &str, current_pkg: &str) -> String {
    // Map ogham std types → google.protobuf well-known types
    if let Some(wkt) = well_known_proto_type(full_name) {
        return wkt.to_string();
    }

    match package_from_full_name(full_name) {
        Some(pkg) if pkg != current_pkg => {
            format!("{}.{}", proto_package(pkg), name)
        }
        _ => name.to_string(),
    }
}

/// Collect google/protobuf/*.proto imports needed by WKT references in this bundle.
fn collect_wkt_imports(bundle: &PkgBundle) -> BTreeSet<String> {
    let mut wkt_full_names = BTreeSet::new();

    let mut collect_from_ref = |tr: Option<&TypeReference>| {
        collect_wkt_from_type_ref(tr, &mut wkt_full_names);
    };

    for ty in &bundle.types {
        for f in &ty.fields {
            collect_from_ref(f.r#type.as_ref());
        }
        for o in &ty.oneofs {
            for f in &o.fields {
                collect_from_ref(f.r#type.as_ref());
            }
        }
    }
    for svc in &bundle.services {
        for rpc in &svc.rpcs {
            if let Some(ref p) = rpc.input {
                collect_from_ref(p.r#type.as_ref());
            }
            if let Some(ref p) = rpc.output {
                collect_from_ref(p.r#type.as_ref());
            }
        }
    }

    // Convert full_names to import paths, dedup
    wkt_full_names
        .iter()
        .filter_map(|name| wkt_proto_import(name))
        .map(|s| s.to_string())
        .collect()
}

fn collect_wkt_from_type_ref(tr: Option<&TypeReference>, out: &mut BTreeSet<String>) {
    let tr = match tr {
        Some(t) => t,
        None => return,
    };
    match &tr.kind {
        Some(type_reference::Kind::MessageType(m)) => {
            if well_known_proto_type(&m.full_name).is_some() {
                out.insert(m.full_name.clone());
            }
            for f in &m.fields {
                collect_wkt_from_type_ref(f.r#type.as_ref(), out);
            }
        }
        Some(type_reference::Kind::EnumType(e)) => {
            if well_known_proto_type(&e.full_name).is_some() {
                out.insert(e.full_name.clone());
            }
        }
        Some(type_reference::Kind::Map(m)) => {
            collect_wkt_from_type_ref(m.key.as_deref(), out);
            collect_wkt_from_type_ref(m.value.as_deref(), out);
        }
        _ => {}
    }
}

/// Map ogham std full_name to its proto import path.
fn wkt_proto_import(full_name: &str) -> Option<&'static str> {
    match full_name {
        s if s.starts_with("struct.") => Some("google/protobuf/struct.proto"),
        "time.Timestamp" => Some("google/protobuf/timestamp.proto"),
        "time.Duration" => Some("google/protobuf/duration.proto"),
        s if s.starts_with("wrappers.") => Some("google/protobuf/wrappers.proto"),
        s if s.starts_with("any.") => Some("google/protobuf/any.proto"),
        _ => None,
    }
}

/// Map ogham std full_name to google.protobuf well-known type.
fn well_known_proto_type(full_name: &str) -> Option<&'static str> {
    match full_name {
        // struct package
        "struct.Struct" => Some("google.protobuf.Struct"),
        "struct.Value" => Some("google.protobuf.Value"),
        "struct.ListValue" => Some("google.protobuf.ListValue"),
        "struct.NullValue" => Some("google.protobuf.NullValue"),
        // time package
        "time.Timestamp" => Some("google.protobuf.Timestamp"),
        "time.Duration" => Some("google.protobuf.Duration"),
        // wrappers
        "wrappers.BoolValue" => Some("google.protobuf.BoolValue"),
        "wrappers.BytesValue" => Some("google.protobuf.BytesValue"),
        "wrappers.DoubleValue" => Some("google.protobuf.DoubleValue"),
        "wrappers.FloatValue" => Some("google.protobuf.FloatValue"),
        "wrappers.Int32Value" => Some("google.protobuf.Int32Value"),
        "wrappers.Int64Value" => Some("google.protobuf.Int64Value"),
        "wrappers.StringValue" => Some("google.protobuf.StringValue"),
        "wrappers.UInt32Value" => Some("google.protobuf.UInt32Value"),
        "wrappers.UInt64Value" => Some("google.protobuf.UInt64Value"),
        // any
        "any.Any" => Some("google.protobuf.Any"),
        _ => None,
    }
}

fn scalar_to_proto(kind: i32) -> String {
    match ScalarKind::try_from(kind) {
        Ok(ScalarKind::Bool) => "bool",
        Ok(ScalarKind::String) => "string",
        Ok(ScalarKind::Bytes) => "bytes",
        Ok(ScalarKind::Int8) | Ok(ScalarKind::Int16) | Ok(ScalarKind::Int32) => "int32",
        Ok(ScalarKind::Int64) => "int64",
        Ok(ScalarKind::Uint8) | Ok(ScalarKind::Uint16) | Ok(ScalarKind::Uint32) => "uint32",
        Ok(ScalarKind::Uint64) => "uint64",
        Ok(ScalarKind::Float) => "float",
        Ok(ScalarKind::Double) => "double",
        _ => "bytes",
    }
    .to_string()
}

fn rpc_param_to_proto(param: Option<&RpcParam>, current_pkg: &str) -> String {
    let param = match param {
        Some(p) => p,
        None => return "google.protobuf.Empty".to_string(),
    };

    if param.is_void {
        return "google.protobuf.Empty".to_string();
    }

    let mut s = String::new();
    if param.is_stream {
        s.push_str("stream ");
    }
    s.push_str(&type_ref_to_proto(param.r#type.as_ref(), current_pkg));
    s
}

fn literal_to_string(lit: &AnnotationLiteral) -> String {
    use annotation_literal::Value;
    match &lit.value {
        Some(Value::StringValue(s)) => format!("\"{}\"", s),
        Some(Value::IntValue(i)) => i.to_string(),
        Some(Value::FloatValue(f)) => f.to_string(),
        Some(Value::BoolValue(b)) => b.to_string(),
        _ => "...".to_string(),
    }
}

fn bundle_has_annotations(bundle: &PkgBundle) -> bool {
    bundle.types.iter().any(|t| {
        !t.annotations.is_empty()
            || t.fields.iter().any(|f| !f.annotations.is_empty())
            || t.oneofs.iter().any(|o| {
                !o.annotations.is_empty()
                    || o.fields.iter().any(|f| !f.annotations.is_empty())
            })
    }) || bundle
        .enums
        .iter()
        .any(|e| !e.annotations.is_empty() || e.values.iter().any(|v| !v.annotations.is_empty()))
        || bundle.services.iter().any(|s| {
            !s.annotations.is_empty() || s.rpcs.iter().any(|r| !r.annotations.is_empty())
        })
}
