// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: oghamproto/compiler/request.proto

package compiler

import (
	ir "github.com/oghamlang/go/oghamproto/ir"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Severity int32

const (
	Severity_SEVERITY_NONE Severity = 0
	Severity_ERROR         Severity = 1
	Severity_WARNING       Severity = 2
	Severity_INFO          Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_NONE",
		1: "ERROR",
		2: "WARNING",
		3: "INFO",
	}
	Severity_value = map[string]int32{
		"SEVERITY_NONE": 0,
		"ERROR":         1,
		"WARNING":       2,
		"INFO":          3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_oghamproto_compiler_request_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_oghamproto_compiler_request_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_oghamproto_compiler_request_proto_rawDescGZIP(), []int{0}
}

// Sent to a plugin via stdin. Contains the fully resolved IR.
type OghamCompileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Compiler version that produced this request.
	CompilerVersion string `protobuf:"bytes,1,opt,name=compiler_version,json=compilerVersion,proto3" json:"compiler_version,omitempty"`
	// The module being compiled.
	Module *ir.Module `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	// Plugin options from ogham.gen.yaml `opts` section.
	Options map[string]string `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Output directory specified in ogham.gen.yaml.
	OutputDir     string `protobuf:"bytes,4,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OghamCompileRequest) Reset() {
	*x = OghamCompileRequest{}
	mi := &file_oghamproto_compiler_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OghamCompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OghamCompileRequest) ProtoMessage() {}

func (x *OghamCompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_compiler_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OghamCompileRequest.ProtoReflect.Descriptor instead.
func (*OghamCompileRequest) Descriptor() ([]byte, []int) {
	return file_oghamproto_compiler_request_proto_rawDescGZIP(), []int{0}
}

func (x *OghamCompileRequest) GetCompilerVersion() string {
	if x != nil {
		return x.CompilerVersion
	}
	return ""
}

func (x *OghamCompileRequest) GetModule() *ir.Module {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *OghamCompileRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *OghamCompileRequest) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

// Returned by a plugin via stdout.
type OghamCompileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*GeneratedFile       `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Errors        []*CompileError        `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OghamCompileResponse) Reset() {
	*x = OghamCompileResponse{}
	mi := &file_oghamproto_compiler_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OghamCompileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OghamCompileResponse) ProtoMessage() {}

func (x *OghamCompileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_compiler_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OghamCompileResponse.ProtoReflect.Descriptor instead.
func (*OghamCompileResponse) Descriptor() ([]byte, []int) {
	return file_oghamproto_compiler_request_proto_rawDescGZIP(), []int{1}
}

func (x *OghamCompileResponse) GetFiles() []*GeneratedFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *OghamCompileResponse) GetErrors() []*CompileError {
	if x != nil {
		return x.Errors
	}
	return nil
}

// A file produced by a plugin.
type GeneratedFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path relative to output_dir.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// File contents.
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// If true, content is appended to existing file instead of overwriting.
	Append        bool `protobuf:"varint,3,opt,name=append,proto3" json:"append,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedFile) Reset() {
	*x = GeneratedFile{}
	mi := &file_oghamproto_compiler_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedFile) ProtoMessage() {}

func (x *GeneratedFile) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_compiler_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedFile.ProtoReflect.Descriptor instead.
func (*GeneratedFile) Descriptor() ([]byte, []int) {
	return file_oghamproto_compiler_request_proto_rawDescGZIP(), []int{2}
}

func (x *GeneratedFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GeneratedFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GeneratedFile) GetAppend() bool {
	if x != nil {
		return x.Append
	}
	return false
}

// An error reported by a plugin.
type CompileError struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Message  string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Severity Severity               `protobuf:"varint,2,opt,name=severity,proto3,enum=oghamproto.compiler.Severity" json:"severity,omitempty"`
	// Optional: source location that caused the error.
	SourceType    string `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceField   string `protobuf:"bytes,4,opt,name=source_field,json=sourceField,proto3" json:"source_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileError) Reset() {
	*x = CompileError{}
	mi := &file_oghamproto_compiler_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileError) ProtoMessage() {}

func (x *CompileError) ProtoReflect() protoreflect.Message {
	mi := &file_oghamproto_compiler_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileError.ProtoReflect.Descriptor instead.
func (*CompileError) Descriptor() ([]byte, []int) {
	return file_oghamproto_compiler_request_proto_rawDescGZIP(), []int{3}
}

func (x *CompileError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CompileError) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_NONE
}

func (x *CompileError) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *CompileError) GetSourceField() string {
	if x != nil {
		return x.SourceField
	}
	return ""
}

var File_oghamproto_compiler_request_proto protoreflect.FileDescriptor

const file_oghamproto_compiler_request_proto_rawDesc = "" +
	"\n" +
	"!oghamproto/compiler/request.proto\x12\x13oghamproto.compiler\x1a\x19oghamproto/ir/types.proto\"\x9b\x02\n" +
	"\x13OghamCompileRequest\x12)\n" +
	"\x10compiler_version\x18\x01 \x01(\tR\x0fcompilerVersion\x12-\n" +
	"\x06module\x18\x02 \x01(\v2\x15.oghamproto.ir.ModuleR\x06module\x12O\n" +
	"\aoptions\x18\x03 \x03(\v25.oghamproto.compiler.OghamCompileRequest.OptionsEntryR\aoptions\x12\x1d\n" +
	"\n" +
	"output_dir\x18\x04 \x01(\tR\toutputDir\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x01\n" +
	"\x14OghamCompileResponse\x128\n" +
	"\x05files\x18\x01 \x03(\v2\".oghamproto.compiler.GeneratedFileR\x05files\x129\n" +
	"\x06errors\x18\x02 \x03(\v2!.oghamproto.compiler.CompileErrorR\x06errors\"U\n" +
	"\rGeneratedFile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x16\n" +
	"\x06append\x18\x03 \x01(\bR\x06append\"\xa7\x01\n" +
	"\fCompileError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x129\n" +
	"\bseverity\x18\x02 \x01(\x0e2\x1d.oghamproto.compiler.SeverityR\bseverity\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12!\n" +
	"\fsource_field\x18\x04 \x01(\tR\vsourceField*?\n" +
	"\bSeverity\x12\x11\n" +
	"\rSEVERITY_NONE\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\b\n" +
	"\x04INFO\x10\x032r\n" +
	"\x0eOghamPluginAPI\x12`\n" +
	"\aCompile\x12(.oghamproto.compiler.OghamCompileRequest\x1a).oghamproto.compiler.OghamCompileResponse\"\x00B-Z+github.com/oghamlang/go/oghamproto/compilerb\x06proto3"

var (
	file_oghamproto_compiler_request_proto_rawDescOnce sync.Once
	file_oghamproto_compiler_request_proto_rawDescData []byte
)

func file_oghamproto_compiler_request_proto_rawDescGZIP() []byte {
	file_oghamproto_compiler_request_proto_rawDescOnce.Do(func() {
		file_oghamproto_compiler_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oghamproto_compiler_request_proto_rawDesc), len(file_oghamproto_compiler_request_proto_rawDesc)))
	})
	return file_oghamproto_compiler_request_proto_rawDescData
}

var file_oghamproto_compiler_request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_oghamproto_compiler_request_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_oghamproto_compiler_request_proto_goTypes = []any{
	(Severity)(0),                // 0: oghamproto.compiler.Severity
	(*OghamCompileRequest)(nil),  // 1: oghamproto.compiler.OghamCompileRequest
	(*OghamCompileResponse)(nil), // 2: oghamproto.compiler.OghamCompileResponse
	(*GeneratedFile)(nil),        // 3: oghamproto.compiler.GeneratedFile
	(*CompileError)(nil),         // 4: oghamproto.compiler.CompileError
	nil,                          // 5: oghamproto.compiler.OghamCompileRequest.OptionsEntry
	(*ir.Module)(nil),            // 6: oghamproto.ir.Module
}
var file_oghamproto_compiler_request_proto_depIdxs = []int32{
	6, // 0: oghamproto.compiler.OghamCompileRequest.module:type_name -> oghamproto.ir.Module
	5, // 1: oghamproto.compiler.OghamCompileRequest.options:type_name -> oghamproto.compiler.OghamCompileRequest.OptionsEntry
	3, // 2: oghamproto.compiler.OghamCompileResponse.files:type_name -> oghamproto.compiler.GeneratedFile
	4, // 3: oghamproto.compiler.OghamCompileResponse.errors:type_name -> oghamproto.compiler.CompileError
	0, // 4: oghamproto.compiler.CompileError.severity:type_name -> oghamproto.compiler.Severity
	1, // 5: oghamproto.compiler.OghamPluginAPI.Compile:input_type -> oghamproto.compiler.OghamCompileRequest
	2, // 6: oghamproto.compiler.OghamPluginAPI.Compile:output_type -> oghamproto.compiler.OghamCompileResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_oghamproto_compiler_request_proto_init() }
func file_oghamproto_compiler_request_proto_init() {
	if File_oghamproto_compiler_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oghamproto_compiler_request_proto_rawDesc), len(file_oghamproto_compiler_request_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oghamproto_compiler_request_proto_goTypes,
		DependencyIndexes: file_oghamproto_compiler_request_proto_depIdxs,
		EnumInfos:         file_oghamproto_compiler_request_proto_enumTypes,
		MessageInfos:      file_oghamproto_compiler_request_proto_msgTypes,
	}.Build()
	File_oghamproto_compiler_request_proto = out.File
	file_oghamproto_compiler_request_proto_goTypes = nil
	file_oghamproto_compiler_request_proto_depIdxs = nil
}
