// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: oghamproto/compiler/request.proto

package compiler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OghamPluginAPI_Compile_FullMethodName = "/oghamproto.compiler.OghamPluginAPI/Compile"
)

// OghamPluginAPIClient is the client API for OghamPluginAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC service for remote plugins (ogham serve --plugin <name> --address :50051).
type OghamPluginAPIClient interface {
	// Unary: compile a module and return generated files.
	Compile(ctx context.Context, in *OghamCompileRequest, opts ...grpc.CallOption) (*OghamCompileResponse, error)
}

type oghamPluginAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewOghamPluginAPIClient(cc grpc.ClientConnInterface) OghamPluginAPIClient {
	return &oghamPluginAPIClient{cc}
}

func (c *oghamPluginAPIClient) Compile(ctx context.Context, in *OghamCompileRequest, opts ...grpc.CallOption) (*OghamCompileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OghamCompileResponse)
	err := c.cc.Invoke(ctx, OghamPluginAPI_Compile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OghamPluginAPIServer is the server API for OghamPluginAPI service.
// All implementations must embed UnimplementedOghamPluginAPIServer
// for forward compatibility.
//
// gRPC service for remote plugins (ogham serve --plugin <name> --address :50051).
type OghamPluginAPIServer interface {
	// Unary: compile a module and return generated files.
	Compile(context.Context, *OghamCompileRequest) (*OghamCompileResponse, error)
	mustEmbedUnimplementedOghamPluginAPIServer()
}

// UnimplementedOghamPluginAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOghamPluginAPIServer struct{}

func (UnimplementedOghamPluginAPIServer) Compile(context.Context, *OghamCompileRequest) (*OghamCompileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Compile not implemented")
}
func (UnimplementedOghamPluginAPIServer) mustEmbedUnimplementedOghamPluginAPIServer() {}
func (UnimplementedOghamPluginAPIServer) testEmbeddedByValue()                        {}

// UnsafeOghamPluginAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OghamPluginAPIServer will
// result in compilation errors.
type UnsafeOghamPluginAPIServer interface {
	mustEmbedUnimplementedOghamPluginAPIServer()
}

func RegisterOghamPluginAPIServer(s grpc.ServiceRegistrar, srv OghamPluginAPIServer) {
	// If the following call panics, it indicates UnimplementedOghamPluginAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OghamPluginAPI_ServiceDesc, srv)
}

func _OghamPluginAPI_Compile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OghamCompileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OghamPluginAPIServer).Compile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OghamPluginAPI_Compile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OghamPluginAPIServer).Compile(ctx, req.(*OghamCompileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OghamPluginAPI_ServiceDesc is the grpc.ServiceDesc for OghamPluginAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OghamPluginAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oghamproto.compiler.OghamPluginAPI",
	HandlerType: (*OghamPluginAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compile",
			Handler:    _OghamPluginAPI_Compile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oghamproto/compiler/request.proto",
}
