// @generated by protoc-gen-es v2.11.0 with parameter "import_extension=ts,json_types=true,valid_types=legacy_required+protovalidate_required,target=ts"
// @generated from file oghamproto/common/source.proto (package oghamproto.common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file oghamproto/common/source.proto.
 */
export const file_oghamproto_common_source: GenFile = /*@__PURE__*/
  fileDesc("Ch5vZ2hhbXByb3RvL2NvbW1vbi9zb3VyY2UucHJvdG8SEW9naGFtcHJvdG8uY29tbW9uIigKClNvdXJjZVNwYW4SDQoFc3RhcnQYASABKA0SCwoDZW5kGAIgASgNImkKDlNvdXJjZUxvY2F0aW9uEgwKBGZpbGUYASABKAkSKwoEc3BhbhgCIAEoCzIdLm9naGFtcHJvdG8uY29tbW9uLlNvdXJjZVNwYW4SDAoEbGluZRgDIAEoDRIOCgZjb2x1bW4YBCABKA1CK1opZ2l0aHViLmNvbS9vZ2hhbWxhbmcvZ28vb2doYW1wcm90by9jb21tb25iBnByb3RvMw");

/**
 * Byte range in source text.
 *
 * @generated from message oghamproto.common.SourceSpan
 */
export type SourceSpan = Message<"oghamproto.common.SourceSpan"> & {
  /**
   * @generated from field: uint32 start = 1;
   */
  start: number;

  /**
   * @generated from field: uint32 end = 2;
   */
  end: number;
};

/**
 * Byte range in source text.
 *
 * @generated from message oghamproto.common.SourceSpan
 */
export type SourceSpanJson = {
  /**
   * @generated from field: uint32 start = 1;
   */
  start?: number;

  /**
   * @generated from field: uint32 end = 2;
   */
  end?: number;
};

export type SourceSpanValid = SourceSpan;

/**
 * Describes the message oghamproto.common.SourceSpan.
 * Use `create(SourceSpanSchema)` to create a new message.
 */
export const SourceSpanSchema: GenMessage<SourceSpan, {jsonType: SourceSpanJson, validType: SourceSpanValid}> = /*@__PURE__*/
  messageDesc(file_oghamproto_common_source, 0);

/**
 * Location in a source file.
 *
 * @generated from message oghamproto.common.SourceLocation
 */
export type SourceLocation = Message<"oghamproto.common.SourceLocation"> & {
  /**
   * @generated from field: string file = 1;
   */
  file: string;

  /**
   * @generated from field: oghamproto.common.SourceSpan span = 2;
   */
  span?: SourceSpan;

  /**
   * @generated from field: uint32 line = 3;
   */
  line: number;

  /**
   * @generated from field: uint32 column = 4;
   */
  column: number;
};

/**
 * Location in a source file.
 *
 * @generated from message oghamproto.common.SourceLocation
 */
export type SourceLocationJson = {
  /**
   * @generated from field: string file = 1;
   */
  file?: string;

  /**
   * @generated from field: oghamproto.common.SourceSpan span = 2;
   */
  span?: SourceSpanJson;

  /**
   * @generated from field: uint32 line = 3;
   */
  line?: number;

  /**
   * @generated from field: uint32 column = 4;
   */
  column?: number;
};

export type SourceLocationValid = SourceLocation;

/**
 * Describes the message oghamproto.common.SourceLocation.
 * Use `create(SourceLocationSchema)` to create a new message.
 */
export const SourceLocationSchema: GenMessage<SourceLocation, {jsonType: SourceLocationJson, validType: SourceLocationValid}> = /*@__PURE__*/
  messageDesc(file_oghamproto_common_source, 1);

